### ISSUE TITLE
Zope 4 WSGIPublisher: exception views are rendered outside of pubevents

### ISSUE THREAD

**Issue by davisagli** [zopefoundation/Zope#102]
Currently the WSGIPublisher first publishes the request running within the transaction_pubevents context manager, then catches any exception and tries to render an exception view. This makes for some regressions compared to how exception views used to work:
1. The PubBeforeAbort event is not called after the exception view produces a response. (This is one place where plone.transformchain hooks in, so it means that Diazo themes are not applied to exception view responses.)
2. The PubFailure event is called before the exception view is rendered, which means that the request is no longer registered as active with zope.globalrequest.

I'm thinking maybe rendering exception views actually belongs within the `publish` function.

**Comment by davisagli** [comment]
Rather than adding exception view rendering into `publish`, I propose that we move the `except` block of `_publish_response` into a function called `_err_hook`, and make the following change in publish_module:

```diff
-                response = _publish_response(
-                    request, response, module_info, _publish=_publish)
+                with transaction_pubevents(request):
+                    try:
+                        response = _publish(request, module_info)
+                    except Exception as exc:
+                        tm.doom()
+                        response = _err_hook(exc, request)
```

We should then probably also make `transaction_pubevents` notify PubBeforeAbort and PubFailure rather than PubBeforeCommit and PubSuccess in the case where the transaction was doomed. I think.

**Comment by hannosch** [comment]
Ok, the regression makes sense. The new WSGI publisher is based on the WSGI publisher in Zope 2.13, which didn't support exception views at all, so I added them in the wrong spot.

For doomed transactions, we can make up some new meaning. Zope 2.13 only had minimal support for them as part of its custom transaction manager (https://github.com/zopefoundation/Zope/blob/2.13/src/Zope2/App/startup.py#L299). If you tried to commit a doomed transaction it instead aborted it. But otherwise it didn't change anything and had no effect on the response.

For Zope 4 I've got rid of the custom transaction manager and just use the default one from transaction. That one should raise a DoomedTransaction exception, when trying to commit a doomed transaction. So to get the old behavior back, I've added the "silently abort doomed transaction" logic to the publisher.

For the _err_hook idea, calling `tm.doom` on any exception isn't the right thing to do. Raising any of the HTTPExceptions representing 2xx or 3xx codes shouldn't be considered a failure. While these are exceptions, they represent successful responses and both publication events and transaction status should reflect that. But you can still intercept these via exception views. This is one new Pyramid inspired feature we got, as part of getting the full list of HTTPExceptions.

For the _err_hook you also need to pass in the pre-created response. Unfortunately Zope creates both a request and response instance before any publication happens and makes the response available as `request.RESPONSE`. That means you can start modifying the response during publication, for example add headers or cookies and the publication result should reflect those changes.

Exception views are also weird as a result of this. Calling the exception view only produces the body of a response, but not a full response instance. In order to modify headers or set the status of the response, the view needs to do ``request.RESPONSE.setStatus()``. I think that pattern is weird and unfortunate, but don't think we can change it now.

**Comment by leorochael** [comment]
> For the _err_hook idea, calling tm.doom on any exception isn't the right thing to do. Raising any of the HTTPExceptions representing 2xx or 3xx codes shouldn't be considered a failure. While these are exceptions, they represent successful responses and both publication events and transaction status should reflect that. But you can still intercept these via exception views. This is one new Pyramid inspired feature we got, as part of getting the full list of HTTPExceptions.

I've seen code in ERP5, and before that on CMFWorkflow, that relied on the fact that raising a Redirect exception aborted the transaction.

The protocol I've seen used in Zope is like this:

 * If, in the middle of a transaction, you discover that the user should be doing something else, you **raise** a `Redirect` instance to abort the transaction and send the user on his way.

 * On the other hand, if you do want to finish the transaction AND redirect the user, you **return** the `Redirect` exception (or simply call `response.redirect`).

So, special-casing exceptions and not dooming the transactions might surprise some people and create hard-to-debug errors.

**Comment by hannosch** [comment]
`response.redirect` raises a Redirect exception in Zope 4, so that distinction is gone. Similarly many places in the code raise Redirect directly, or in other cases raise BadRequest instead of returning a MessageDialog instance.

But looking at both the publisher and WSGI publisher in Zope 2.13, I think you are right. Raising Redirect so far always aborted the transaction. So the special handling I mentioned should only apply to HTTPOk (2xx) codes. One new feature of Zope 4 is that you can register exception views for IRedirect, in Zope 2.13 the exception hook just re-raised Redirect before it did the view lookup.

**Comment by leorochael** [comment]
> `response.redirect` raises a Redirect exception in Zope 4's WSGI publisher, so that distinction is gone. 

This is going to cause pain for the code bases not expecting an exception to be raised here.

> Similarly many places in the code raise Redirect directly, or in other cases raise BadRequest instead of returning a MessageDialog instance.

Code bases raising `Redirect` directly for now are getting exactly what they're asking for, so it shouldn't be a problem.

**Comment by hannosch** [comment]
Hhm. Come to think of it, one common use-case is creating a new object, adding it to the ZODB and than redirecting to its default view.

So it might be better to commit transaction on redirect by default and let people use `transaction.doom` for those cases where they want to abort the current publication.

**Comment by leorochael** [comment]
> So it might be better to commit the transaction on redirect by default and let people use transaction.doom for those cases where they want to abort the current publication.

I'm -1 on any semantic where raising an exception does not abort the transaction (I'm -0 on not aborting HTTP 2XX exceptions).

What's the trouble with returning a redirection when you don't want to abort, instead of raising it?

**Comment by davisagli** [comment]
> For the _err_hook idea, calling tm.doom on any exception isn't the right thing to do. Raising any of the HTTPExceptions representing 2xx or 3xx codes shouldn't be considered a failure. While these are exceptions, they represent successful responses and both publication events and transaction status should reflect that. But you can still intercept these via exception views. This is one new Pyramid inspired feature we got, as part of getting the full list of HTTPExceptions.

I figured that out and on the `plonezope4` branch I have a change similar to what I proposed above,  but it only dooms the transaction for responses with a status >= 400: https://github.com/zopefoundation/Zope/commit/9fa1f14e1f78b7f0592780d9531d0264f1cf8326

> For the _err_hook you also need to pass in the pre-created response. Unfortunately Zope creates both a request and response instance before any publication happens and makes the response available as request.RESPONSE. That means you can start modifying the response during publication, for example add headers or cookies and the publication result should reflect those changes.

Sure, but _err_hook can also get the response from request.response

I can prepare a pull request from what we've got in the `plonezope4` branch (which also has unrelated changes), but I need to take a closer look at redirects.

**Comment by leorochael** [comment]
> Hhm. Come to think of it, one common use-case is creating a new object, adding it to the ZODB and than redirecting to its default view.

Exactly. Conversely, a use case of aborting on Redirect is to trap an unauthorized access and redirect the user to the login form.

**Comment by davisagli** [comment]
> Exactly. Conversely, a use case of aborting on Redirect is to trap an unauthorized access and redirect the user to the login form.

In this case the redirect status can be set as part of rendering the Unauthorized exception view. There's no Redirect instance involved (either as a return value or raised exception).

But I agree that there are use cases for issuing a redirect response both with and without triggering exception handling.

I took another look at how the handling of redirects affects Plone. The change to make `response.redirect()` raise an exception breaks a bunch of tests for 2 reasons:
1. There are views that call `response.redirect()` and then do further processing. As noted above they expect calling response.redirect to not abort the transaction. In addition, they are expecting this call to not stop execution. A noteworthy example is the Dexterity edit view, which calls redirect and then notifies subscribers of a EditFinishedEvent.
2. In prior Zope releases, redirects made using response.redirect are followed by the test browser even when it has `handleErrors = False`. That's because the method always sets the response status and Location header regardless of the handleErrors setting. With Zope master, where response.redirect raises an exception, that exception falls through to the test code when the test browser has handleErrors = False set and there is thus no exception middleware.

**Comment by pbauer** [comment]
Currently we have 26 failing test due to this issue in http://jenkins.plone.org/view/PLIPs/job/plip-zope4. It ould be great to have a workaround undtil you agree on a lasting implementation.

**Comment by hannosch** [comment]
I think we have solved all the issues mentioned here. Redirects happen again via response.redirect, and those do not use an exception. The testbrowser should follow those as well.

Exception views got moved inside the pubevents/transaction context manager, so events like PubFailure happen again after them. The zope.globalrequest set/clear calls are happening directly inside the publisher code and no longer use events, so `getRequest` works even inside the PubStart event, in exception views as well as in the PubFailure event now.
