### ISSUE TITLE
query-parameters on post-request no longer supported with new ZopeFieldStorage

### ISSUE THREAD

**Issue by mtoepfl** [zopefoundation/Zope#1122]
## BUG/PROBLEM REPORT / FEATURE REQUEST

First of all: Thanks for your hard work you all do on this project. Zope feels really, really professional maintained at the moment! Every thing is stable and works like a charm. I only got one small issue caused by refactoring the ZopeFieldStorage part.

### What I did:

Our zope-instance is behind a Apache-Webserver which does a sub-request to zope over mod_proxy.

We use RewriteRules like this:
`Rewrite (de|en)/view.json http://localhost:8080/some/dir/view_json?project_id=123&language_key=$1 [L,P]`

If I do a `POST`-request to the `/de/view.json` with `Content-type: application/json`, query-params are added by Apache, Zope raises a `NotImplementedError("request parameters and body")` in the latest version.

This worked for many years. Two days ago I updated our staging-system to Zope-5.8.1 and it broke.

I think it`s not an error to have both, query-params and a request-body, in one http-request according to http-standard, is it?

### What I expect to happen:

Add the query-parameters and the request-body to the HTTPRequest-instance like Zope did before.
So no Exception.

### What actually happened:

Zope raises a `NotImplementedError("request parameters and body")`

### What version of Python and Zope/Addons I am using:

Zope-5.8.1
Python 3.11

### What helped

As always I was a little bit stressed, so I needed a quick fix. So I patched two lines:

removed:
https://github.com/zopefoundation/Zope/blob/6977b8880d0c18d9befb1699c437bc1346bafc1c/src/ZPublisher/HTTPRequest.py#L1441

added `self._file = fs.file` before:
https://github.com/zopefoundation/Zope/blob/6977b8880d0c18d9befb1699c437bc1346bafc1c/src/ZPublisher/HTTPRequest.py#L523

I also tried to add a test-case in the style of `test_processInputs_xxx` but this seems to be a little bit complicated for this use-case (`_makePostEnviron`). So I decided to spend my time in writing a good issue, sorry.

Whould be gread, if you find a better solution than me and bring it upstream! 

Thanks again

Michael

**Comment by mtoepfl** [comment]
@d-maurer Look's like you did the work on the `ZopeFieldStorage` part. Thank you for that. Would you mind to take a look at my quick fix and give me some feedback if it's enough. If it takes less time to fix it yourself, than giving me feedback, feel free to fix it yourself. I'm unfortunately not very experienced in doing pull requests.

**Comment by ale-rt** [comment]
@mtoepfl could you check if this branch works for you: #1117

**Comment by mtoepfl** [comment]
@ale-rt Thank`s for your fast repsonse. 

Sorry doesn`t work. 

`if method == "POST":` is True in my case and you changed the elif-branch in same if-statement.

https://github.com/zopefoundation/Zope/blob/a50e15a83eda95b269b9e8461b98048c6c4925d6/src/ZPublisher/HTTPRequest.py#L1423

Also the `self._file = fs.file` part is missing. 

But your problem with restapi seems similar. 

Did you try a `POST`-request on restapi with query-parameters?
Should not work with your fix.

Sorry for closing/reopening. Github UI is broken on my smartphone.

**Comment by d-maurer** [comment]
mtoepfl wrote at 2023-4-21 05:13 -0700:
>@d-maurer Look's like you did the work on the `ZopeFieldStorage` part.

Right.

>Thank you for that. Would you mind to take a look at my quick fix and give me some feedback if it's enough.

I can explain why `Zope` raises a `NotImplementedError`.
It is not because query parameters on POST requests were an error by the spec
but because it cannot handle query parameters in this case as
it usually does. Therefore, it raises
`NotImplementedError` with the meaning "sorry, I did not implement this case".

Usually, `Zope` processes query parameters to get items
for `request.form`.
The respective code is in `ZPublisher.HTTPRequest.HTTPRequest.processInputs`.
It makes the distinction:
either the fieldstorage does not have the attribute `list`
(this means some special request) or it has the attribute.
In the latter case, the `list` attribute is expected to contain
all request parameters (query parameters are part of of the request
parameters) and they are processed to give `request.form` items.

Your change avoids the exception but it does not
ensure that the query parameters get processed to `request.form`
items.
The  query parameters can only be accessed
raw (i.e. unprocessed) as `request.environ["QUERY_STRING"]`.


Ideally, `Zope` would handle query parameters always in the same
way - i.e. make them available raw in `request.environ["QUERY_STRING"]`
and processed into `request.form` items.

If it does not do this, it should clearly tell so.
Currently, it does this with an `NotImplementedError`.
Alternatively, it could also document the limitation
and its behavior for special cases (like yours).

**Comment by mtoepfl** [comment]
@d-maurer Thank`s for your detailed explanation. I think, I got it.

So in our case we have to suppress the NotImplementedError. But self.list is defined because of the query-parameters in the url_qs-variable. So the if-condition `not hasattr(fs, 'list')` in processInputs is False. In the else branch there is no `self._file = fs.file`, so my body is empty. If I add it, it works.

https://github.com/zopefoundation/Zope/blob/a50e15a83eda95b269b9e8461b98048c6c4925d6/src/ZPublisher/HTTPRequest.py#L1410

Isn't the only case in which the request-body needs to be converted in key-value-pairs and added to "list" if contentType is `application/x-www-form-urlencoded`? In all other cases the "self._file = fs.file" is needed to get access the body afterwards, isn`t it?

**Comment by d-maurer** [comment]
mtoepfl wrote at 2023-4-21 10:38 -0700:
> ...
>Isn't the only case in which the request-body needs to be converted in key-value-pairs and added to "list" if contentType is `application/x-www-form-urlencoded`? In all other cases the "self._file = fs.file" is needed to get access the body afterwards, isn`t it?

Request parameters can come from the query string or
a body with `Content-Type`
`application/x-www-form-urlencoded` or `multipart/form-data`.

My reasoning is that request parameters should always result
in items for `request.form`.
The current code cannot do this for query string parameters
if the request body has a `Content-Type` different from those above.
Therefore, it raises a `NotImplementedError` in this case --
indicating that this case is not implemented.

To get rid of this, `HTTPRequest.processInputs` would need to
get refactored.
It should not expect that the FieldStorage has either `list` or `file`
but can have both -- and handle this case correctly.


If you are a Zope contributor, you could provide a pull request.
I would help as needed.

**Comment by d-maurer** [comment]
@mtoepfl Would you check whether #1124 fixes this issue?

**Comment by mtoepfl** [comment]
I tested it out and it works perfectly fine. Your changes in #1124 solve my issues.

Thank you very much @d-maurer! 

I`m going to close this issue when your pull request is merged.
