### ISSUE TITLE
Provide Early Hints support

### ISSUE THREAD

**Issue by gforcada** [zopefoundation/Zope#1185]
## BUG/PROBLEM REPORT / FEATURE REQUEST

There's a "new" standard [Early Hints](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103).

If I understood it right: the server can send, before the request is fully processed, some headers back to the client with hints on which servers the client will have to connect, resources that could already be downloaded, etc

This can improve the overall perceived performance of the responses.

Cloudflare made an [article about it](https://blog.cloudflare.com/early-hints/).

Would that be something that Zope can/should support, or it is something that should be dealt in other parts of the stack? i.e. `waitress` or any wsgi server, or a wsgi middleware..

**Comment by d-maurer** [comment]
Gil Forcada Codinachs wrote at 2023-11-22 02:06 -0800:
>There's a "new" ( standard [Early Hints](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103).
>
>If I understood it right: the server can send, before the request is fully processed, some headers back to the client with hints on which servers the client will have to connect, resources that could already be downloaded, etc

The intermediate informational responses do not play well
with the WSGI interface:
For WSGI, a request is mapped to one call of the application object.
The application processes the request and signals the availability
of the response headers via the `start_response` callback
and returns an iterator producing the response body.
There is no room for an intermediate response.

"https://peps.python.org/pep-3333/#http-1-1-expect-continue"
describes how WSGI can handle "100-continue" despite this restriction.
As you can see, the WSGI server must provide special support
because the application usually does not have access to the response channel.
The same would be true for the new informational "103-hint" response.

A WSGI extension could allow the application to issue intermediate
responses, e.g. issue the new "103-hint" response.
One possibility would be to give the application access to the
response channel.
It would be WSGI server specific whether it supports such an extension.


The "103-hints" extension mostly targets sites which link to
external resources.
I usually recommend to serve all essential resources (e.g. CSS, JS) locally
because this reduces the risk that essential resouces
are temporarily unavailable.

Do you really see a need for "103-hints" for typical Zope/Plone
applications?

**Comment by gforcada** [comment]
I don't have an urgent need. I read about it and wondered if either Zope already had support for it, or how complex it would be to add it 😄 

For our use case, a newspaper site, that has quite some external integrations, it would indeed be noticeable this perceived performance that one can get via this 103 responses.

**Comment by d-maurer** [comment]
Gil Forcada Codinachs wrote at 2023-11-24 09:58 -0800:
>I don't have an urgent need. I read about it and wondered if either Zope already had support for it, or how complex it would be to add it ?
>
>For our use case, a newspaper site, that has quite some external integrations, it would indeed be noticeable this perceived performance that one can get via this 103 responses.


The main stumbling block is the WSGI limitation not supporting
that the application generates intermediate responses.
Thus, look for corresponding configuration features
before the WSGI server or of the WSGI server itself.

**Comment by gforcada** [comment]
Ok, cool, thanks, then we can close this for now, and instead focus on getting the support at the WSGI servers first 👍🏾

**Comment by d-maurer** [comment]
Gil Forcada Codinachs wrote at 2023-11-29 13:26 -0800:
>Ok, cool, thanks, then we can close this for now, and instead focus on getting the support at the WSGI servers first ??

There are several ways:

1. the restriction for multiple calls to `start_response` is lifted for 1xx
   responses. This would allow an application to create
   intermediate 1xx responses by calling `start_response` for them.

2. the WSGI server provides access to the output channel
   (e.g. via a `wsgi.output` in analogy to `wsgi.input`).
   The application could then generate intermediate responses
   writing directly to the output channel and use the normal
   WSGI way for the "final" response

3. the WSGI server handles 103 responses itself -- in analogy
   to its "100 continue" handling

4. the Web server (in contrast to the WSGI server) generates
   intermediate 1xx responses

For 3. and 4., the respective server needs configuration to
tell it when to generate intermediate responses.
