### ISSUE TITLE
Instructions to install in a virtualenv are not working

### ISSUE THREAD

**Issue by jcea** [zopefoundation/Zope#194]
Documentation in https://zope.readthedocs.io/en/2.13/INSTALL-virtualenv.html describes this procedure to install Zope inside a virtualenv:

```
(virtualenv)# bin/pip install \
  --trusted-host download.zope.org \
  --index http://download.zope.org/Zope2/index/2.13.26/ Zope2
Collecting Zope2
  Could not find a version that satisfies the requirement Zope2 (from
versions: )
No matching distribution found for Zope2
```

Documentation needs to be fixed :).

Details in this mailing list thread: https://mail.zope.org/pipermail/zope/2017-August/176764.html

**Comment by hannosch** [comment]
It looks like the supported index format changed with pip 8.0.0. Following the provided instructions with pip 7.1.2 works as expected.

**Comment by jcea** [comment]
Should it be better to support PIP > 8.0.0 since current release is >9.0?. Downgrading PIP seems an ugly hack...

**Comment by hannosch** [comment]
Zope 2.13 is seven years old now and requires lots of old versions of all kinds of libraries. It shouldn't really be surprising, that it also needs older installation tools (both pip and buildout).

Since the release is basically in security-fix only mode, I don't think adding support for a different installation scheme is in-scope for it anymore.

If you need modern tool and language support, Zope 4 has now reached the beta phase and supports the latest versions of buildout and pip.

**Comment by icemac** [comment]
@jcea In #198 I documented the install procedure using a current `pip` version. It is published on https://zope.readthedocs.io/en/2.13/INSTALL-virtualenv.html#install-the-zope2-2-13-26-software-packages Surprisingly it was not that difficult.
