### ISSUE TITLE
WebDAV: bad charset handling in "PROPPATCH"

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#21]
Zope2 2.13.10

I send the following "PROPPATCH" command to a Plone object (which uses
"utf-8" as charset for its properties):

```
<propertyupdate xmlns='DAV:'>\n  <set><prop><title
xmlns='http://www.zope.org/propsets/default'>k\xc3\xa4lander.xml</title></prop></set>\n</propertyupdate>
```
In "webdav.xmltools.Node.strval" the incoming property value
u"kälander.xml" in encoded in a so called "zope_encoding", defined as
"latin-1". At least for properties of Plone objects, this is the wrong
encoding.

**Comment by tseaver** [comment]
The [`xmltools` code on the 2.13 branch](https://github.com/zopefoundation/Zope/blob/593c97450ae0051257cbd1de84d5e15afad2660d/src/webdav/xmltools.py#L64) uses `latin-1` in order to stay compatible with the [`OFS.PropertySheets` implementation](https://github.com/zopefoundation/Zope/blob/593c97450ae0051257cbd1de84d5e15afad2660d/src/OFS/PropertySheets.py#L789).

The `master` branch uses `utf-8` instead in both places.
