### ISSUE TITLE
manage_pasteObjects breaks when pasting many objects

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#217]
[_cb_decode](https://github.com/zopefoundation/Zope/blob/2.13/src/OFS/CopySupport.py#L686) only allows 8 kB of compressed copy data.
This was introduced in https://github.com/zopefoundation/Zope/commit/6ca369193cb3292aca0824216dbe1775c65ff8be to prevent a DoS attack.

The curent implementation also prevents pasting many objects in file system code be calling e.g.:

```python 

dest.manage_pasteObjects(source.manage_copyObjects(ids))
```

I propose a new parameter to `manage_pasteObjects` to override the `maxsize` value of `_cb_decode` to support this use case again or to use a different value if `cb_copy_data` is not `None` when calling `manage_pasteObjects`.

What do you think of my proposal?

This issue exists on Zope 2.13 and Zope 4.

See also https://stackoverflow.com/questions/17581962/copyerror-ofs-copysupport-manage-pasteobjects-limited-to-160-objects

**Comment by tseaver** [comment]
ISTM that allowing TTW code to override that count is a Bad Thing (TM).

Maybe split the methods into the TTW-callable `manage_{copy,paste}Objects` and an underlying `_{copy,paste}Objects` which takes that flag?

**Comment by jan-jockusch** [comment]
In our use cases, using the TTW interface to move massive amounts of code via copy/paste is a normal thing in Zope. I'd have a hard time telling my users that they're attempting DoS in version 4 with an action that was totally OK in version 2.13. 
If this is a serious concern, can we make the feature at least configurable, please? I can attempt a patch (since I'll have to make sure this works for my installations anyway).

**Comment by hannosch** [comment]
We could also make the default size a zope.conf option and look it up from there.

I think gunicorn's `limit-request-field-size` (http://docs.gunicorn.org/en/stable/settings.html#limit-request-field-size) and waitress' `max_request_header_size` (https://docs.pylonsproject.org/projects/waitress/en/latest/arguments.html) serve a similar purpose here. Those apply length constraints on the size of all headers or on each header. A per-header upper length limit would already limit the size of the `Set-Cookie` header, so maybe this would be enough here?

Otherwise we could make it an additional config option, specific to zlib decompression.

**Comment by icemac** [comment]
@jan-jockusch This problem only will strike you if you select many, many objects in a folder and copy them to another place. I do not think there is a problem when copying TTW as copying a folder needs only the reference (physical path) to the folder but not to each of its contained objects in the REQUEST.

The behaviour of `_cb_decode` described in this issue did not change beetween Zope 2.13 and Zope 4. It was introduced in 2.13.21 as a security fix and I'd like to keep the security level introduced there.

@hannosch You suggestion sounds a bit like an overkill as the current limit can only be hit when copying many objects from a single folder (this is what we do programmatically where I hit this issue). I do not think that it will be a problem from TTW code as we have 8 kByte of z-compressed text at the highest compression level containing the physical paths of the objects which should be copied excluding contents of folders.

I think the suggestion of @tseaver is most suitable for the problem.

**Comment by icemac** [comment]
See also https://stackoverflow.com/questions/17581962/copyerror-ofs-copysupport-manage-pasteobjects-limited-to-160-objects for a temporary solution.

**Comment by icemac** [comment]
Fix needs to be ported to 2.13, too.

**Comment by icemac** [comment]
Fixed via #269 (master) resp. #270 (2.13).
