### ISSUE TITLE
Enabling travis-ci tests for 2.13 branches of Zope dependencies 

### ISSUE THREAD

**Issue by hannosch** [zopefoundation/Zope#230]
I've just enabled recurring travis-ci tests for the 2.13 branches of Zope dependencies. These run once a month if they weren't triggered before that. Tests for master still run once a week, unless triggered by some other activity. This is using Travis-CI's "Cron Jobs" feature.

Given the recent setuptools/buildout/pypi changes, I expect most of these to fail, especially under Python 2.6, which is still supported on a best-effort basis for Zope 2.13. If you come across any failures, the following combination might work to get tests running again:

zopefoundation/Acquisition@7d67af03c58e612e4dad7616e579c9b1ca4f17af

My hope is we might get the tests on the 2.13 branches to green, so once the new security fixes drop, we don't have to debug and fix the test environment at the same time.

**Comment by dataflake** [comment]
@icemac This can be closed, right? The branch is indeed tested (at least during pushes), the tests succeed and the problematic Python 2.6 support has been removed.

**Comment by icemac** [comment]
I think @hannosch suggested to test the 2.13 branches of Acquisition, RestrictedPython, ExtensionClass etc. This is not done, yet. I am not sure if it is worth the required work.

I'd keep it open for now.

@mauritsvanrees You upvoted this issue. Do you see improved value in it for the Plone project?

**Comment by mauritsvanrees** [comment]
I think this issue is indeed about the dependencies used by Zope.

Zope 2.13 and friends are still used by all currently supported non-beta versions of Plone. The [Jenkins server of Plone](https://jenkins.plone.org) is testing the Plone code, but not any Zope code. So if Zope 2.13 and related packages are regularly tested on Travis, that would be good.
Mostly, it would be good to have a working Travis before a possible future security fix would need to be added (nothing planned at the moment).

No one has stepped up so far. For example Acquisition 2.13 is tested on Travis, but the last build was [a year ago](https://travis-ci.org/zopefoundation/Acquisition/builds/310014829). It passed then, but that may not be the case today. At least Python 2.6 is still in the test mix there, which is likely to fail.

So I'd keep this issue open for now. May be a nice task on a sprint, or on a rainy day.
But of course the attention would be better focused on getting Zope 4 ready for a final release. There is only so much volunteer time that can be put into maintaining old branches.

**Comment by dataflake** [comment]
@mauritsvanrees Do you still think this is relevant? I doubt anyone will ever touch this.

**Comment by mauritsvanrees** [comment]
Plone 4.3-5.1 are still using these, so they are still relevant to Plone, so Travis jobs would be good to have.
And a month ago @jugmac00 cared enough to [fix Travis for Acquisition 2.13](https://github.com/zopefoundation/Acquisition/commit/a62179fcb8d349b2abaab7f5c847a8129bb3a8a9).
But it seems unlikely that someone will voluntarily do the work. Having this issue open did not help so far.

**Comment by dataflake** [comment]
There certainly isn't anyone on the Zope side who wants to spend any time on Zope 2.13 issues at this point, unless it's some emergency fix. I am going to close this here, there's no good reason left for this to keep clogging up the issue tracker.

**Comment by jugmac00** [comment]
Hi @mauritsvanrees 
whenever I have to wait for a build or my test runs to finish, I try to give back something to the Zope community, sometimes by fixing broken tests or by bumping/dropping Python versions.

Setting up Travis from scratch with all its initial quirks and expected test failures for so many projects is unfortunately out of scope. Especially, as when I have some more time, I try to update the extensive Zope documentation which is partially extremely outdated.

You can count the regular Zope committers on the fingers of one or two hands.

How long will the Plone versions, which are dependent on Zope 2.13, be supported by the Plone team?

Maybe it would be possible for the Plone community to tackle this issue?

Well, speaking of Plone/Zope communities... after the merger of the foundations, we should think of one community anyway.
