### ISSUE TITLE
Add Products.ZCatalog 2.13.29 to versions.cfg of Zope 2.13

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Zope#253]
I am talking about this file: http://download.zope.org/Zope2/index/2.13.26/versions.cfg
I'm not sure if it is wise to change that file, or if that should end up in a future 2.13.27 release.
I also don't know where this file is copied from, so where to change it.

Plone has its own adapted version of this, at http://dist.plone.org/versions/zope-2-13-26-versions.cfg. We had our own version for a while, to avoid DNS and downtime problems of download.zope.org.

It is linked from http://dist.plone.org/release/4.3.17-pending/versions.cfg, which additionally pins `Products.ZCatalog 2.13.29`, like I propose in this issue.

**Comment by tseaver** [comment]
ISTM that we should *not* be updating the pinned version of any product for an already-released Zope2's `versions.cfg` file.

Those files represent the versions which were "known good" at the time the corresponding Zope2 release was made.  It should be standard practice that folks extend those files to provide local overrides.

**Comment by mauritsvanrees** [comment]
Agreed. I updated the issue title to update the version in 2.13, so a future release.

**Comment by icemac** [comment]
@mauritsvanrees Zope 2.13.26 is no longer the latest Zope2 release. In Innsbruck during the Alpine City Sprint I released version 2.13.27. Its version pins are on https://zopefoundation.github.io/Zope/ as the new canonical place. That new Zope version already contains `Products.ZCatalog = 2.13.29`.

@tseaver When creating the Zope 2.13.27 release I did not create a new index directory on download.zope.org because I do not have permissions to log in into that server and because the index can only be used by `easy_install` but not by `pip` (see #198). Do we still need these index directories for new releases?

**Comment by mauritsvanrees** [comment]
Gah! Did I *really* completely forget to update the Zope2 version pin in Plone??? I guess I was glad that my changes were merged and released, and then stopped thinking... :-( Well, I went on with other stuff at that same Alpine City Sprint, but anyway...

Sigh, my bad. I will take this up in Plone. (cc @esteele)

Sorry for the noise. I will close this issue.

**Comment by tseaver** [comment]
@icemac As long as we are no longer documenting the use of those index pages, I think we are fine to avoid creating them.
