### ISSUE TITLE
ZOracleDA support of zope-2.13.26 and above

### ISSUE THREAD

**Issue by vamsi4482** [zopefoundation/Zope#266]
ZOracleDA not supported in zope-2.13.26.?
so how to connected to Oracle 11 and above DBs via zope-2.13.26

**Comment by dataflake** [comment]
Speaking about ZOracleDA itself, that code has not seen updates in more than 15 years and is clearly dead.

**Comment by leorochael** [comment]
Since ZOracleDA is an add-on, it's the responsibility of the ZOracleDA codebase to to make sure it's compatible with newer Zope releases, rather the other way around.

I was going to suggest opening an issue against the ZOracleDA repository, wherever it is supposed to be, but a cursory search leads me to the same conclusion as @dataflake: it's dead and unmaintained.

[The page for the DCOracle2 distribution (that actually contained the ZOracleDA) on the old Zope site ](http://old.zope.org/Members/matt/dco2/) mentions that the code was kept on the (currently dead) [CVS repository](http://cvs.zope.org/Products/DCOracle2/), and furthermore that:

> DCOracle2 is currently unmaintained, and no support is available.

Where "currently" above actually means "since 2003".

Hence no place to file a bug report.

Instead, I'm going to suggest that anyone wanting to use ZSQL methods to talk to an Oracle database (or any other SQL database really) should probably try their hand with [`SQLAlchemyDA`](https://github.com/zopefoundation/Products.SQLAlchemyDA) instead.

All this to say that I'm closing this issue as out of scope.
