### ISSUE TITLE
Activate Chameleon caching on hard disk by default

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#291]
Chameleon needs an environment variable pointing to a directory, see https://chameleon.readthedocs.io/en/latest/configuration.html#general-usage

Caching on hard disk speeds up using Chameleon PageTemplate a lot, even in tests.

~~At least it should be documented what to do when using Zope in an application.~~ Done in #461.

**Comment by dataflake** [comment]
@icemac I mistakenly checked the fix directly into `master` in 97e7ea9c19315b311c9996d2dbc27398dba9226e, apologies. Since it's not affecting any existing Zope instances and only changes the creation of new WSGI instances I think it's OK.

Please close once you have taken a look. I tested it manually by creating a new instance and then visiting a few page templates. The cache files showed up as expected under `$INSTANCE/var/cache`.

**Comment by icemac** [comment]
@dataflake Thank you for fixing this issue. Your code change looks good to me.
