### ISSUE TITLE
Provide single source of documentation

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#293]
At the moment the Zope2 book is "officially" published both at
- https://docs.zope.org/zope2/zope2book/index.html and
- https://zope.readthedocs.io/en/latest/zope2book/index.html

On https://docs.zope.org/zope2/index.html additionally you can read:
"Release specific information can be found at: https://zope.readthedocs.org" - when clicking the link you get redirected to zope.readthedocs.io.

Do both sites provide the latest version of the documentation?
Why is the documentation provided on two different locations?

Imho, there should be only one location for the documentation.

I'd suggest to remove the Zope 2 book from docs.zope.org and put a link to https://zope.readthedocs.io/en/latest/zope2book/index.html

Also, docs.zope.org contains some broken links, ie the links in the ZODB section are all broken.

I could not find the index.txt from docs.zope.org in the github repo, so I could not provide a pull request.

**Comment by rbu** [comment]
Good idea, let's use the sprint next week to find out who has access to the docs site and put in redirects.

**Comment by dataflake** [comment]
Did anyone ever find out what's driving the content behind docs.zope.org? It's still a big mix where some pieces do link to zope.readthedocs.io, some don't, and some stuff is just plain broken.

**Comment by dataflake** [comment]
By the way, the path under http://docs.zope.org/developer is apparently fed by the repository https://github.com/zopefoundation/developer_docs

**Comment by jugmac00** [comment]
I'd bet @tseaver or @jimfulton have an answer for this.

**Comment by jugmac00** [comment]
It seems the TLS  certificate for docs.zope.org went invalid yesterday (but in the meanwhile a new one was issued).

![Screenshot_20190501-221025](https://user-images.githubusercontent.com/9895620/57059172-45a70e80-6cb4-11e9-876a-22b8590e4d2d.png)


> Did anyone ever find out what's driving the content behind docs.zope.org?
Maybe we can find out more about how to proceed with docs.zope.org at next weeks sprint.

**Comment by dataflake** [comment]
@tseaver @jimfulton I just wish we got access to at least edit and rebuild that landing page on docs.zope.org. That would help **a whole lot**. I fear the effort being spent on updating everything on zope.readthedocs.io is not getting adequate visibility because everyone will automatically go to docs.zope.org first which shows outdated information.

**Comment by dataflake** [comment]
FYI, Tres has created a login for me on the server that hosts docs.zope.org. I'll take a look around later today to see how the site content is set up and where I can start improving it.

**Comment by dataflake** [comment]
@icemac @jugmac00 @tseaver Please take a look at docs.zope.org now. The contents are now in the new repository https://github.com/zopefoundation/docs.zope.org. This is what I changed:

- cleaned up the links on the front page
- removed links to the documentation for single packages because all that was six years old
- switched to the same RTD Sphinx theme we use on zope.readthedocs.io

I did not go over any of the other content like the `zope_secrets` subfolder, or the Developer Docs repository at https://github.com/zopefoundation/developer_docs, which links into http://docs.zope.org/developer/. Anyone is welcome to make changes now.

When I stepped in there I realized that site content is something I had set up myself. I had totally forgotten about it. The sources were "lost" because they came from the defunct svn.zope.org and were never ported to GitHub. From the dates on the files it appears that setup was created in mid-2010 and last touched in March 2013.

**Comment by mgedmin** [comment]
> The sources were "lost" because they came from the defunct svn.zope.org and were never ported to GitHub.

I've a mirror of the SVN repo, if you want it: https://zope3.pov.lt/trac/browser/docs.zope.org_website.  (It's not directly accessible via a subversion client, but if you wish I can git svn clone and push it to github or something.)

**Comment by dataflake** [comment]
@mgedmin Thanks, I don't need it. I got access to the original checkout and have moved that to GitHub. There's no need to convert that old repository.

**Comment by dataflake** [comment]
FYI: We are now all set as far as access to hosting is concerned so this can begin in earnest.

My 5 cents:

- www.zope.org (repo: https://github.com/zopefoundation/www.zope.org/) should become the main documentation hub
- the contents of docs.zope.org (repo: https://github.com/zopefoundation/docs.zope.org/) should be merged into www.zope.org and then the docs.zope.org repo should be retired
- the website docs.zope.org should just redirect to www.zope.org, the redirect configuration should ensure old paths will still get the desired result
- the developer documentation (repo: https://github.com/zopefoundation/developer_docs) should be merged into www.zope.org and then the developer_docs repo should be retired.
- there are several other repositories with documentation that transcends specific packages and those should be looked at and, if it makes sense, merged into www.zope.org. See https://github.com/zopefoundation?utf8=%E2%9C%93&q=doc&type=&language=
- The Zope Book and the Zope Developers Guide would also be good candidates for being moved to www.zope.org as they touch more than just the core Zope package. zope.readthedocs.io should only contain documentation very specific to the Zope package.

**Comment by dataflake** [comment]
Issue #236 can be folded into this one

**Comment by dataflake** [comment]
@jugmac00 I'm going to close this issue as resolved. I suggest opening new issues when moving other documentation resources in https://github.com/zopefoundation/www.zope.org.
