### ISSUE TITLE
broken objects are rendered with the ID `broken` in ZMI

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#311]
This prevents from deleting them via ZMI because the ID and thus the URLs are wrong.

This seems to be the case since the merge of #249.

See screenshot:
<img width="891" alt="bildschirmfoto 2018-09-03 um 10 53 20" src="https://user-images.githubusercontent.com/386619/44977273-e992bb80-af67-11e8-912a-78f7bb672c85.png">

**Comment by tseaver** [comment]
I don't see anything in the diff for #249 which would have changed this (the string `broken` only appears in the `brokenEdit.dtml` part of the diff.

**Comment by rbu** [comment]
Let's put this on the agenda for the sprint

cc @drfho @dwt

**Comment by icemac** [comment]
@rbu I already put it to 
https://github.com/orgs/zopefoundation/projects/1#card-12950537

**Comment by viktordick** [comment]
At the moment, broken objects prevent the ZMI from being rendered at all, due to the same issue.
The problem is that `main.zpt` iterates over `objectValues()` (instead of `objectItems()`, like it was done in `main.dtml` in 2.13). This relies on the object itself providing information like its ID, which is not the case for broken objects (and might even in some weird cases differ from the ID under which the object is found below its parent).
