### ISSUE TITLE
Circular dependency Zope and Products.OFSP

### ISSUE THREAD

**Issue by tomgross** [zopefoundation/Zope#36]
The two packages Zope and Products.OFSP depend on each other in setup.py

**Comment by tomgross** [comment]
Can it be remove from Zope? It is only used (installed?) in ZopeTestCase. Probably having it in buildout.cfg is sufficient.

**Comment by tseaver** [comment]
[Products.OFSP](https://github.com/zopefoundation/Products.OFSP) exists to make the "core" objects ZMI addable, and to register images / online help for them:

- DTMLDocument
- DTMLMethod
- Image
- File
- Folder
- OrderedFolder
- UserFolder

It is properly a dependency of Zope-the-application-server, but not of Zope-the-libraries.

**Comment by leorochael** [comment]
I'd suggest moving the OFS packages from Zope into `Products.OFSP` to break the cycle.

**Comment by tseaver** [comment]
Can't happen:  too many third-party products expect to import things from `OFS`.  Nobody expects that code to live in a product.  `Products.OFSP` is *only* about registering stuff for the ZMI, not about the underlying Python implementations.

We could maybe break the cycle by making `Products.OFSP` an `extras_require` dependency, e.g.:

```python
    extras_require={
        'appserver': ['Products.OFSP'],
    },
```

But we'd then have to tell people to install `Zope2[appserver]` pretty much everywhere.

**Comment by leorochael** [comment]
Or maybe pull a ZODB 4 and have Zope2 be the package that is the appserver that depends on Zope the library, Products.OFSP (containing OFS), etc.,

I have a dream where we actually turn ZServer into a wsgi server capable of serving FTP, mapping it to WebDAV commands (besides HTTP, obviously), and Zope contains ZPublisher (and the Request/Response classes). Zope2 would pull them together.

**Comment by hannosch** [comment]
When I split out Products.OFSP, I had a similar idea of eventually moving OFS into the same project (maintaining it's module/package name).

The problem is that OFS depends on things in App and App depends on things in OFS, and the same in other places. These circular dependencies where too many for me to go ahead and try to break out OFS.

Since then I removed HelpSys, which removed 90% of the code from Products.OFSP. It's basically just a init file with an initialize function for OFS content. It needs to be in the Products namespace for that to be picked up.

Now I'd probably rather go back and move OFSP back into the Zope2 project, as it makes little sense on its own.
