### ISSUE TITLE
Shutdown https://bugs.launchpad.net/zope2

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#365]
... or at least make it read only, and maybe provide a link to our Github site.

https://bugs.launchpad.net/zope2

**Comment by dataflake** [comment]
@tseaver @zopyx @ctheune  I have assigned you here because you have administrator-level access to that Launchpad issue tracker and/or the project as a whole. Could you find out if there's a way to "freeze" or disable that issue tracker and either make it redirect to `https://github.com/zopefoundation/Zope/issues` or put a prominent note on it so people know where to go?

Thanks!

**Comment by zopyx** [comment]
I am actually not member of the LP team 
<img width="577" alt="screenshot 2019-02-18 09 08 32" src="https://user-images.githubusercontent.com/594239/52936582-d8463b80-335c-11e9-8b96-ac1bc542baa3.png">

**Comment by dataflake** [comment]
@zopyx you have Administrator role in the "Zope Developers" group who are "Bug Supervisors" on that issue tracker: https://launchpad.net/~zope2-dev/+members#active. I guessed that gave you some kind of admin-level control over it.

**Comment by zopyx** [comment]
I can only remove the team  or ask the LP admins for removal of the complete project. I don't see any particular option for nailing down the issue tracker to readonly.

**Comment by dataflake** [comment]
@icemac @jugmac00 @zopyx I think asking LP admins to remove the complete project is perfectly fine. There's noting of value in there anymore. The damage of people hitting dead links to LP is more than outweighed by the fact that what they would see there is completely outdated.

**Comment by icemac** [comment]
+1 from me to completely remove Zope from LP. Old bugs do not matter so much and the new ones are here on GitHub.

**Comment by dataflake** [comment]
@zopyx Could you set that in motion please?

**Comment by dataflake** [comment]
@zopyx Any news on shutting down the Launchpad presence?

**Comment by dataflake** [comment]
@zopyx Could you please ask the LP admins to remove the project? Thanks!

**Comment by zopyx** [comment]
Sorry, this issue disappeared from radar...will care about it

**Comment by zopyx** [comment]
https://answers.launchpad.net/launchpad/+question/683589

**Comment by dataflake** [comment]
Great, thanks! It's Labor Day in the US, so feedback may not be immediate.

**Comment by dataflake** [comment]
@icemac I see you're also directly subscribed to the Launchpad issue Andreas created. I have deleted my Launchpad account years ago and don't want to create one again, could you comment on that discussion as well? Here's some points:

The continued presence of Zope projects on Launchpad is a huge distraction and confuses people. The Launchpad content has been outdated and unmaintained for many years because there is no point in (and no volunteers for) maintaining two infrastructures, GitHub and Launchpad. The argument that there are open issues in various bug trackers is bogus. We had made the conscious decision many years ago to not copy every single issue over. Nothing that still exists on Launchpad is relevant or holds any value. It distracts and confuses.

**Comment by dataflake** [comment]
I have created a list of projects for them to delete and added that to a new Launchpad question because the old old got expired again and I did not see a way to get it back to an active status. %$#@. The new question is at https://answers.launchpad.net/launchpad/+question/685285

The list is a result of going through every project on all groups I am a member of, and checking it against the packages mentioned in the current `requirements-full.txt`. I personally don't care about all those old Zope 3-only packages.

**Comment by dataflake** [comment]
Colin from Launchpad has either deleted or marked all projects from my followup in https://answers.launchpad.net/launchpad/+question/685285 as archived. It's also no longer possible to create new trouble tickets there. This is now resolved. The only Zope-related projects not treated this way are Zope 3-only that are not used in Zope (4) anymore. Anyone who cares about them can contact Launchpad themselves.

**Comment by jugmac00** [comment]
@dataflake Thanks for your effort!
