### ISSUE TITLE
Provide screenshots and/or video of new ZMI

### ISSUE THREAD

**Issue by tomgross** [zopefoundation/Zope#378]
For promotional purposes some screenshots of the new and shiny ZMI should be included in the documentation.

Also an animated gif (like in https://github.com/pypa/pipenv/blob/master/README.md) would be cool.

**Comment by icemac** [comment]
Great idea, a PR is welcome.

**Comment by dataflake** [comment]
Since a PR doesn't seem to be forthcoming and it makes no sense to leave this issue open forever I have added a few screen shots in e5ab3bf7600c6d717ec0113521e4605710300ce1, see https://zope.readthedocs.io/en/latest/zope4/news.html#restyled-zope-management-interface-zmi. I'm going to close this issue.

If anyone is willing to spend more time on it they should open a new issue, and that issue won't be on the critical path for the final Zope 4 release.

**Comment by icemac** [comment]
@dataflake Thank you for tackling this issue.
