### ISSUE TITLE
Circular dependency Zope and Products.ZCatalog

### ISSUE THREAD

**Issue by tomgross** [zopefoundation/Zope#38]
The two packages Zope and Products.ZCatalog depend on each other in setup.py

**Comment by tseaver** [comment]
I believe the dependency in Zope is because:

- Zope [imports from `Products.ZCatalog.Lazy`](https://github.com/zopefoundation/Zope/blob/master/src/ZTUtils/Zope.py#L22):  I think the only correct fix is to move that module wholesale into `ZTUtils`, and leave behind a backward-compatibility shim in `Products.ZCatalog`.
- Zope still handles ]registering the "deprecated add/delete" handling on behalf of two  ZCatalog classes](https://github.com/zopefoundation/Zope/blob/master/src/OFS/deprecated.zcml#L21-L24).  The fix would be to move that handling into `Products.ZCatalog:configure.zcml` (or, even better, [fix them](https://github.com/zopefoundation/Zope/blob/master/src/OFS/event.txt#L89)).
