### ISSUE TITLE
Remove DTML and replace with ZPT

### ISSUE THREAD

**Issue by tomgross** [zopefoundation/Zope#40]
Remove DTML and replace with ZPT or even  in Zope 4.

**Comment by hannosch** [comment]
I've rewritten DocumentTemplate in pure Python, which should make it considerably easier to port to Python 3 - once its dependencies are ported that is.

I think that's actually less work overall, rather than trying to rewrite all the arcane DTML documents into ZPT and preserving the functionality of them. I'm hoping we can remove lots of those DTML documents when we remove more and more of the ZMI.

**Comment by leorochael** [comment]
Many dtml snippets in the code can be usefully replaced by python methods returning the equivalent interpolated strings.
