### ISSUE TITLE
fast-listen equivalent on with WSGI server

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#416]
In Zope 2 it was possible open to the listener port early instead of the end of the startup phase. It might be controversial if this  is a good thing or not - at least it is convenient during the development phase when you start up an instance that might take some time (e.g. Plone with many add-ons) and start the first request (and do something different inbetween until Plone renders the first page). Is there something similar doable with the WSGI server?

**Comment by icemac** [comment]
It seems to be a good idea but I even did not know about this feature in Zope 2.

**Comment by icemac** [comment]
This feature request also exists in plone/plone.recipe.zope2instance#71. @pbauer says there: it has to be  supported by the WSGI server and that `waitress` does not support this feature.

**Comment by dataflake** [comment]
@zopyx It is doable and appears to have been implemented in the latest release of `plone.recipe.zope2instance` after plone/plone.recipe.zope2instance#75 was merged. Can you try that?

**Comment by zopyx** [comment]
Working but buggy 

https://github.com/plone/plone.recipe.zope2instance/issues/86

**Comment by dataflake** [comment]
plone.recipe.zope2instance will be fixed when https://github.com/plone/plone.recipe.zope2instance/pull/94 is merged in.

As far as the original question goes: ``waitress`` itself does not have a direct configuration option for this behavior. Philipp was right on that. But ``waitress`` allows you to hand it a socket that you can create manually beforehand instead of specifying a host and port, and that's what ``plone.recipe.zope2instance`` does:

https://github.com/plone/plone.recipe.zope2instance/blob/22bbaf3613d0552c1c42d5c93480434e6e8e0751/src/plone/recipe/zope2instance/ctl.py#L903-918

The code in ``Zope2.Startup.serve.py``, ``ServeCommand.run`` would have to emulate that.

**Comment by dataflake** [comment]
The feature is completed and released in `plone.recipe.zope2instance`, which is what every single Plone user and developer will most likely be using, which will thus cover Andreas.

@icemac Emulating this functionality in `Zope2.Startup.serve.py` seems like a bad idea because it would only work for `waitress`. The built-in server runner in Zope should stay as agnostic as possible.

I suggest closing this issue here.

**Comment by icemac** [comment]
@dataflake I second keeping Zope agnostic to the WSGI server.
