### ISSUE TITLE
ZMI: Broken copyright link

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#482]
There is a link called "© Zope Foundation" in the left panel, it points to http://localhost:8080/manage_copyright which does not (no longer?) exist:

<img width="572" alt="broken link" src="https://user-images.githubusercontent.com/386619/52519546-d1347480-2c5c-11e9-9c24-2768dc8b9046.png">

Where should this link point to? 
To http://www.zope.org/en/latest/foundation.html?

**Comment by dataflake** [comment]
The old `manage_copyright` shows the text of the ZPL and that Zope is copyrighted to the Zope Foundation. Underneath it showed an outdated Python license, and a super-outdated list of contributors.

Since the Zope Foundation is dead and I haven't heard anything back from the Plone Foundation about their process of taking over there is no page to point that link to that is guaranteed to stay. I wouldn't mind adding a static page in Zope itself with the ZPL text and the copyright notice.
