### ISSUE TITLE
WSGI: WARNI [waitress] application returned too few bytes (0) for specified Content-Length (994) via app_iter

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#513]
Apparently, there is a (minor) `Content-Length` problem in the WSGI interaction.

Clicking in a Plone site on the management page "acl_users/plugins/manage_plugins" on any of the plugins, results in a series of "waitress" warnings of the form: 
```
2019-02-19 10:26:55,962 WARNI [waitress:450][waitress] application returned too few bytes (0) for specified Content-Length (990) via app_iter
2019-02-19 10:26:55,962 WARNI [waitress:450][waitress] application returned too few bytes (0) for specified Content-Length (1003) via app_iter
2019-02-19 10:26:55,966 WARNI [waitress:450][waitress] application returned too few bytes (0) for specified Content-Length (1018) via app_iter
```

**Comment by icemac** [comment]
@d-maurer Could the be a problem in the code behind `acl_users/plugins/manage_plugins`? I have never seen such warnings before, although using Zope 4.0b9 daily in union.cms.

**Comment by d-maurer** [comment]
Meanwhile, I have seen this warning frequently. While is seems quite reproducible with "manage_plugins", in other cases, it happens non deterministically. I conclude from this that it is not an application problem but something in the communication with "waitress".

**Comment by dataflake** [comment]
Just FYI, I have seen the error myself and also within the context of a PluggableAuthService, but at least with current `master` checkouts I don't get them anymore.

I had changed many of the page templates in the product to be more compatible with the new Zope 4 ZMI, that may have made it disappear in this particular place.

Note to whoever looks at this: Install Products.PluggableAuthService version 2.0b2 or earlier.

**Comment by dataflake** [comment]
I take that back: You were talking about the PluginRegistry, but that has seen template changes in the meantime as well. But I have tried with versions 1.6.1 and 1.6 and just can't reproduce it anymore. Not sure where to look right now. ``waitress`` itself had its last release in late January, so that hasn't changed. Maybe it is changes in the Zope code.

**Comment by dataflake** [comment]
OK, figured it out and will put in a fix later. The culprit is objects of type `ImageFile`, like those ugly arrows in some of those forms. ImageFile set `Content-Length` to the file size, but later on checks to see if it can just return a `304` with empty body instead of the file. At that moment the `Content-Length` header needs to be reset to 0.
