### ISSUE TITLE
ZMI: Determining if an object doesn't need/want a modal Add dialog

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#535]
Right now there is a hardcoded list of constructor and product names inside `zmi/styles/resources/zmi_base.js` for items that don't want to show the modal dialog when adding them to a container.

There are many Zope products out there that worked fine before just attempting to redirect to their container without showing an add form, which now pop up the modal dialog that just renders the container contents. And if you dismiss the modal dialog the underlying page shows the old container contents, as if nothing was added.

I think we can agree that the solution is sub-optimal. Third-party authors should be able to set a flag themselves that will prevent the modal from popping up. This could be anything from a new class attribute (they already have to add `zmi_icon` so that's no big deal) or maybe just an added query string item that gets passed with the product's own redirect URL. I'm open for pretty much any solution that allows the product author to decide without asking to have Zope code changed.

**Comment by drfho** [comment]
@dataflake 
yes, a class attribute like add_modal=True|False could solve that issue. This could be rendered (Zope\src\App\dtml\manage_navbar.dtml) as an optional data-attribute (e.g. data-dialog="modal")  into the selectlist and control the JS function _addItem()_
```
<select id="addItemSelect"...>
<option value="manage_addProduct/BTreeFolder2/folderAdd">BTreeFolder2</option>
<option data-dialog="modal"  value="manage_addProduct/Sessions/addIdManager">Browser Id Manager</option>
....
</select>
```
As far as understand you would prefer a whitelist instead of the blacklitsted classes as the better suboptimum?  If you add an add_modal attribute (like the zmi_icon) that is rendered into the addItem-list,  I can modify the JS twisting the logic and using that attribute.
Cheers
fh
