### ISSUE TITLE
ZMI usability: Missing prominent link to go to the ZMI root

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#548]
When the left-hand navigation tree is closed (which happens all the time with the way the URLs are manipulated in the new ZMI) I am missing a prominent link to go to the root's `/manage` or `/manage_main`. I find myself constantly using the small `/` in the breadcrumbs under the ZMI tabs, which is aggravating.

From a usability perspective I would expect such a link to be prominently at the top left. But right now we have "Zope 4" there, which links to www.zope.org instead of some concept of "Home". IMHO that outside link is unexpected in that position, and bad UI for people who accidentally use it because they expect some "Home" link there.

I would really like to see such a "Home"-style link where the "Zope 4" link is right now. If a link to zope.org is desired, I'd just put it into its prior position at the bottom of the left frame.

**Comment by drfho** [comment]
hi @dataflake,
I am thankful that you talk about the issue, Actually the Zope4-design facelift does not really solve that 20 year old UX problem; I only improved the spacing so that the user has a real chance to click onto the root link:
![path_nav](https://user-images.githubusercontent.com/29705216/56096122-569a0680-5ee4-11e9-9b97-e03fbbc85f61.png)
I like your proposal to use the Zope-link in the header as an intuitive alternative to get back to the root node. Whereas a link to zope.org has no practial need for working with Zope, that link could be placed in the left frame. So what about a quickfix: linking the "logo" to the root element and adding the Zope.org-Link to the popup-list before the copyright page link?

BTW: I thought about taking the Zope logo as a symbol for the root node, but the old Zope logo definitely has a graphical a problem: is can not scale smoothly because the line width differences do not take into account any general recommendations for designing (small) icons.
Maybe we could improve that and refresh the logo to contemporary technical needs and add a modern flavor to it?  What do you think about a logo competition, maybe 2 month and then voting. If the results are not convincing, we could stay with the old one.
Cheers
f

**Comment by dataflake** [comment]
Your comparison of the link size in the breadcrumbs is correct, but the premise is wrong. You have opened what is normally a sub-frame into a separate window. I cannot emphasize enough, **no one does that in Zope 2**. People run the full three-frame page where they **always** have the left-hand tree, which acts as such a quick "back to the root" path. So there isn't much need to use the breadcrumbs in Zope 2 specifically to get to the root, which means the link size wasn't a big issue. So IMHO there was no "20 year old UX problem" because people always had much better ways to get to the root.

With that old Zope 2 full-frame page it is also really hard to slip into a single frame filling the main window, like it happens every single time I use a normal browser function like "back" or "reload" with the new ZMI. What's worse, I continually end up resubmitting forms with invalid data when going back in the browser.

You have explained why you are doing the URL manipulation in the URL bar and I get it, but it really is at the root of many of my ongoing complaints about usability. I'm not asking to get rid of it, but for me it's become so bad that today I was thinking I should release a Zope package that adds Java Script and/or CSS to just get rid of those "fake" URLs. For all my use cases it would make the ZMI experience a whole lot better if I get a stable two-frame layout where the left frame stays visible at all times. Apologies for venting.

I'm neutral on how a link to the root of the ZMI should look like. It could just be something generic that people are familiar with, some "home" symbol.

**Comment by drfho** [comment]
hi @dataflake again,
I am sorry, obviously I did not fully understand all the consequences you detected concerning losing form data.  If this is a side effect we definitley should remove the URL correction. 
Actually I came from a different perspective, because none of our customers uses the frameset scenario for the known reasons.  Of course, for them it will be okay if Zope shows a constant URL  in the frameset again.
But now I would like to understand the issue in detail. May I ask you, to show me problem by skype screen-sharing and we quickly discuss it "live"? Tomorrow late afternoon? I will send my skype address tomorrow by e-mail.  Maybe we both will get a niceer idea how to solve it.
Cheers
fh

**Comment by dataflake** [comment]
@drfho In b597fd779328737baf752cb51ebd1da735fee4ff I followed your suggestion from our email conversation to only put ``GET`` URLs into the URL bar. It solves the form resubmission issues.

Do you have any ideas about an always visible element for quick access to the ZMI root? Ideally, it should link to ``/manage`` and not just ``manage_main``.

**Comment by drfho** [comment]
@dataflake: usually it is accepted that a click on the logo brings you back to home/root. So I would prefer to use that pattern and set the zope.org link into the sidebar menu. 
Or because "back to root" is a kind of tree-navigation we could to transform the sitemap/tree-icon to a button that shows a dropdown menu (1. ->root, 2.->sitemap).  
Any favorite ?

**Comment by dataflake** [comment]
@drfho Yes, the logo as anchor feels like a very natural pattern. Sounds good to me.

**Comment by dataflake** [comment]
This was resolved with f1f56a5. Thank you!
