### ISSUE TITLE
Nonsensical PATH_INFO handling in WSGIPublisher.publish_module

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#575]
The code in ``publish_module`` that wants to clean up ``environ['PATH_INFO']`` is broken under Python 3.

- it assumes PATH_INFO is an unencoded string (is this always true under Python3? I don't know.)
- it encodes PATH_INFO in `Latin-1` in one line and decodes it from `UTF-8` in the next line. That's clearly broken.

Commits 6c15c71 by @sallner and 707df73 by @icemac left the code in this state. Please look this over and fix it.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2019-4-28 21:41 -0700:
>The code in ``publish_module`` that wants to clean up ``environ['PATH_INFO']`` is broken under Python 3.
>
>- it assumes PATH_INFO is an unencoded string (is this always true under Python3? I don't know.)
>- it encodes PATH_INFO in `Latin-1` in one line and decodes it from `UTF-8` in the next line. That's clearly broken.

This may (or may not) be correct.

"PATH_IFNO" is one of the "cgi" variables - defined for the
"Common Gateway Interface" between Web servers and scripts.
With this interface, the web server provides information about the request
in environment variables (such as "PATH_INFO").


Python 3 wants to handle the values in 'os.environ` as `str` (and not
as `bytes`). Therefore, it must decode the values provided by the
environment.
I have made some tests to determine how Python 3 chooses the enconding
for the "envvar" decoding. Apparently, this depends on the current
"locale" settings: with the "c" locale, Python uses "latin-1" for the decoding;
with my typical UTF-8 locale (defined by "LANG=de_DE.UTF-8"), it uses
"utf-8".

With this in mind, the `encode("latin-1").decode("utf-8")`
would be correct for the "cgi" case with the "c" locale
if "PATH_INFO" was really encoded `utf-8` (as it should be according
to the uri standard) (it might be wrong for a different locale).


In our case, the `ZPublisher` does not use `os.environ` - but gets
the environment from the WSGI component in front. This has the same
problem as `os.envion`: it gets a sequence of bytes with unknown
encoding and should produce a dict with `str` values.
In this situation, it is quite natural to choose the "transparent encoding"
"latin-1" for the decoding. With this choice, the `ZPublisher` code
would be correct.


Of course, the WSGI front end might choose differently
(I have not verified whether the WSGI standard stipulates the encoding
to use) - and then the `ZPublisher` code would be wrong.


If the `ZPublisher` code should get changed, then parts
of the (functional) test framework would require corresponding changes
as well: I remember to have seen `encode(utf-8).decode("latin-1")`
sequences when working on the Py3 compatibility for the `zope.formlib`
test suite.

**Comment by d-maurer** [comment]
Dieter Maurer wrote at 2019-4-29 11:24 +0200:
>Jens Vagelpohl wrote at 2019-4-28 21:41 -0700:
>>The code in ``publish_module`` that wants to clean up ``environ['PATH_INFO']`` is broken under Python 3.
>>
>>- it assumes PATH_INFO is an unencoded string (is this always true under Python3? I don't know.)
>>- it encodes PATH_INFO in `Latin-1` in one line and decodes it from `UTF-8` in the next line. That's clearly broken.
>
>This may (or may not) be correct.

This is correct -- see below:

> ...
>Of course, the WSGI front end might choose differently
>(I have not verified whether the WSGI standard stipulates the encoding
>to use) - and then the `ZPublisher` code would be wrong.

PEP 3333 (which defines WSGI) stipulates in section "A Note On String Types"
("https://www.python.org/dev/peps/pep-3333/#a-note-on-string-types")
(reformulated below):

  We are using "native string"s (represented as Python's "str") for
  request/response headers and metadata.

  We must use the "latin-1" encoding to get the "bytes value"
  of a "native string".

The section "Unicode Issues"
("https://www.python.org/dev/peps/pep-3333/#unicode-issues")
stresses further that "unicode" ("str" for Python 3) is in fact
restricted to the latin-1 character set.

**Comment by dataflake** [comment]
My concern is twofold:

- if you encode and then immediately decode, why not just leave the string as is?
- there are code points in latin-1 that break in UTF-8, the following example uses "ä":

```
>>> u'\xe4'.encode('latin-1').decode('UTF-8')
Traceback (most recent call last):
...
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 0: unexpected end of data
```

So for this code to work those failing code points must never appear in the incoming PATH_INFO (is this true)? And even then I'm wondering why it isn't just left as native string without that recoding. What sense does that make?

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2019-4-29 04:24 -0700:
>My concern is twofold:

>- if you encode and then immediately decode, why not just leave the string as is?

The recoding is not done for all "native string" metadata but
only for those part of the URL (i.e. "PATH_INFO" and "QUERY_STRING").
The Uri spec stipulates that uris (and therefore urls) should use
the UTF-8 encoding. Therefore, the recoding likely does the right
thing -- and avoids to do it at other places.

>- there are code points in latin-1 that break in UTF-8, the following example uses "ä":

No doubt about this.

But the "latin-1" in this case is not the true encoding of the
binary data. Instead it is the "transparent encoding" which allows
to **view** a byte string as text (aka "native string") without
losing information or make assumptions about the true encoding.

Because the WSGI component (or the Web server) does not know
the real encoding but Python wants a "native string" (for convenience)
it uses "latin-1" (the lossless transformation "bytes -> str").

Knowing that url components should be utf-8 encoded, the publisher
recodes those parts ("PATH_INFO" and "QUERY_STRING") via the
hopefully real encoding "utf-8" -- for further convenience.


> ...
>So for this code to work those failing code points must never appear in the incoming PATH_INFO (is this true)?
>And even then I'm wondering why it isn't just left as native string without that recoding. What sense does that make?

In fact, it is important only for very recent versions of the
uri specification - and it might be even not important at all.

Formerly, the uri specification required ASCII only uris.
Any non-ASCII character was required to be url-encoded.
Only very recently, non-ASCII characters have been allowed in
uris. **BUT** when I remember right then while the restriction has
been removed for "uri"s, it has not been removed for "url"s.
If this is true, then "PATH_INFO" in fact contains only ASCII characters
and for them `.encode("latin-1").decode("utf-8")` is a no op.


With this second thought, the recoding is likely superflous and might
even be counter productive. A recoding should be applied only
after "url-decoding" (i.e. after we see the real utf-8 encoded path,
not its url-encoded form).
In general, we cannot url-decode "PATH_INFO" as a whole (as
the decoding may expose quoted "/" and lead to their mis-interpretation).
Becasue Zope disallows "/" in "id"s, it might be possible for "Zope"
(but "PATH_INFO" might contain non-id elements, e.g. in ";<param>" parts).

Therefore, I (finally) agree with you: the publisher should leave "PATH_INFO"
as it is and any recoding should be done during traversal -- after
the individual path components have been url-decoded.

**Comment by icemac** [comment]
I am going to put this issue on the agenda for the Zope Spring cleaning sprint next week.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-4-29 23:30 -0700:
>I am going to put this issue on the agenda for the Zope Spring cleaning sprint next week.

Short summary of a long discussion:
"PATH_INFO" is part of the url and as such ASCII only (it will
(potentially) contain non-ASCII characters only after url-decoding).
For a sequence "s" of ASCII characters,
`s.encode("latin-1").decode("utf-8") == s`, i.e. the recoding is
in effect a no-op.

However, if Zope wants to support ids with non-ASCII characters
(which seems to be the case), then the recoding must be done eventually
-- after url-decoding has happened.

In the general case, url-decoding cannot be applied to "PATH_INFO"
as a whole (but only to the individual components) - as
it may expose quoted "/" and cause their misinterpretation (as path
separator).
As Zope (currently) does not support "/" in ids nor
uri "param"s, it might be acceptable to url-decode "PATH_INFO"
as a whole. This would effectively prohibit "/" (also) in path components
which do not correspond to ids (e.g. a part of a "traversal subpath"
or a view name).

**Comment by sallner** [comment]
The truth is somewhere in between. 

I investigated the topic as follows. By commenting out the code path in question, the test [test_can_handle_non_ascii_URLs](https://github.com/zopefoundation/Zope/blob/82ff67b3e0efbbde8b2134205c6ceac6b8fc3c76/src/ZPublisher/tests/test_WSGIPublisher.py#L712-L720) breaks. Debugging leads to the conclusion that path_info is latin-1 encoded at this time.
```
-> path_info = path_info.encode('latin-1')
(Pdb) path_info
'/tÃ¤st'
(Pdb) path_info.encode('latin-1')
b'/t\xc3\xa4st'
(Pdb) path_info.encode('latin-1').decode('utf-8')
'/täst'
```
In the tests, 'PATH_INFO' is written by WebOb in [webob/request.py#L1474](https://github.com/Pylons/webob/blob/master/src/webob/request.py#L1474), which uses the [url_unquote](https://github.com/Pylons/webob/blob/b5297529ef5a8dd3dd84c6cfa41afd101acfa8a2/src/webob/compat.py#L117-L131) from compat there. The last step there is a `decode('latin-1')`:
```
((Pdb)) !s
'/t%C3%A4st'
((Pdb)) !unquote(s.encode('ascii'))
b'/t\xc3\xa4st'
((Pdb)) !unquote(s.encode('ascii')).decode('latin-1')
'/tÃ¤st'
```
This is done because of the referenced PEP3333, which requires  
> only code points representable in ISO-8859-1 encoding (\u0000 through \u00FF, inclusive)

The situation is now:
* in `publish_module` we have `text` which was decoded with a non-matching encoding with respect to the content, but with the matching encoding with respect to PEP3333
* to re-decode it, we have to first generate bytes with `latin-1` encoding, and decode afterwards with `utf-8`
* this causes not only an error in the tests, but also in a running instance

For me it does not seem reasonable to push the re-decode in the traverse step, as we would need to do it several times there. If we find a way to test, whether a re-code is needed, it might be a good idea, but it might be that the performance gain is not too significant as there has to be some sort of decoding attempt any way. 

I could try to rephrase the comment in the code and reference this issue here so that there is hopefully less headache for future us.

**Comment by dataflake** [comment]
@sallner If the code as it stands is really OK it needs a BIG comment to explain it. Then you can close it. Otherwise everyone who looks at it will be like "WTF?".

**Comment by sallner** [comment]
> Neither the webserver nor the WSGI interface is allowed to url-decode the url -- as it would remove the difference between a "delimiter" and a "normal" character. "url-decoding" is only allowed after the path is parsed into its components.

Then the source of this fix would be the respective wsgi-server. As Zope is rather a client, then a middleware it seems fine to me, to process the `PATH_INFO` as we need it. 

And actually, there are only ASCII characters in there, as it is a object_id containing unicode characters url-encoded.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2019-5-8 06:20 -0700:
>@d-maurer The URLs you get at that point in the code are coming down the WSGI pipeline. So what PEP-3333 says trumps the HTTP spec.

WSGI must not "url-decode" the url parts -- because "url-decoding"
would remove the distinction between a (semantic) delimiter and
a (passiv) normal character.
If it does, the WSGI component is buggy.

But, if the url is still "url-encoded", it is still ASCII only.

**Comment by dataflake** [comment]
The code we're talking about has nothing to do with URL-decoding or encoding, right? It's all about string encoding and decoding.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2019-5-8 08:30 -0700:
>The code we're talking about has nothing to do with URL-decoding or encoding, right?

No. It has to do with "url-encoding/decoding" -- even though this
is indirect only.

Because WSGI must not "url-decode" (this would destroy
the destinction between (semantically active) delimiters and
(semantically passive) "normal" characters), the
"PATH_INFO" in the environment delivered by WSGI to
the applicatin must still "url-encoded" and therefore pure ASCII.

For "pure ASCII" sequences, both "latin-1" as well as "utf-8" encoding/decoding
are essentially "no-op"s (they change only the type, not the sequence
of code points). Thus, for a "pure ASCII" sequences "s":
   s == s.encode("latin-1").decode("utf-8")


I have read today, that the above encoding/decoding has been introduced
to let a test `test...non_ascii_urls` (or something like that)
succeed. But something else is wrong with this test: strictly
speaking, there are no "non_ascii_urls" (which would be compatible
with HTTP 1.1). Any HTTP 1.1 compatible client would likely
interpret such a thing as an "international uri" and transform
it into an HTTP 1.1 compatible url by applying a proper
decoding (if necessary), then utf-8 encoding, then url-encoding
to arrive at a pure ascii url.
I assume that the "webOb" mentioned in the post does not behave
as an HTTP 1.1 should behave.


>It's all about string encoding and decoding.

But knowing about `PATH_INFO` and the respective standards,
we can deduce that is must be a "no-op" at this place.

The recoding must be done elsewhere -- after the segments of `PATH_INFO` have
been determined and individually url-decoded and indeed
"unquote" (effectively) does this recoding automatically
(in the same way as "quote" works in the other direction).

From `urllib.parse`:
def unquote_to_bytes(string):
    """unquote_to_bytes('abc%20def') -> b'abc def'."""
    # Note: strings are encoded as UTF-8. This is only an issue if it contains
    # unescaped non-ASCII characters, which URIs should not.
    ...
