### ISSUE TITLE
Broken link to Zope Developer’s Guide 2.13 (2.12)

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#585]
**Reproduction**
- open https://zope.readthedocs.io/en/latest/zdgbook/index.html
- scroll to bottom
- click on "latest"
- choose 2.13 or 2.12
=> links are broken

Also, the link behind "On GitHub - View" is broken (which appears also when you hit "latest")

**Comment by dataflake** [comment]
The links are broken because the content simply did not exist in that location on those branches. GitHub doesn't do any checks for that.

I have added redirects for both the developers guide and the Zope Book for the 2.12 and 2.13 branches. They now point to the latest version.

The issue with the "On GitHub - View" is unfixable by us. I have tried all kinds of configuration changes both on RTD and GitHub to make that go away and there already is a (closed) issue for that on here.

**Comment by jugmac00** [comment]
Linking to the actual 2.13 dev guide would have been a perfect solution, as I guess 2.13 will be in production on many legacy sites for years to come. Anyway, at least there is no broken link anymore and when you need the documentation you can build it locally.

**Comment by dataflake** [comment]
@jugmac00 Stupid question, where is that 2.13 dev guide?

**Comment by jugmac00** [comment]
I have to admit I have never ever touched any Read the Docs configuration.

If configuring Read the Docs to also build from the legacy branches ( https://docs.readthedocs.io/en/stable/versions.html )  is too much effort, maybe we can delete the links 2.12 and 2.13? If that is possible for the **dev guide** only, as it seems for other parts the documentation gets build for older branches.

**Comment by dataflake** [comment]
Both the Zope Book and the Developer Guide simply do not exist on the 2.12 and 2.13 branches at all. There is nothing I could point that to. And I can't change the RTD configuration to not show the version links for paths that don't exist in those versions. That's a global configuration for the whole tree of documents. The only thing I can do is those redirects for paths that don't exist on the branches.
