### ISSUE TITLE
Document WSGI deployment

### ISSUE THREAD

**Issue by hannosch** [zopefoundation/Zope#64]
I've tried to update and document a WSGI deployment with modern versions of the stack, but failed so far.

I've added a new runwsgi script (basic copy of Pyramid's pserve, to avoid PasteScript) in 72ae9a1bed26db928e7f74fa063c8de15a755544. I also updated the default mkzopeinstance skeleton to create WSGI config files by default (9ac28c1778ba6dc5b046f187a44435c92b8d6790).

So in a buildout checkout you can currently do:
```
bin/mkzopeinstance -d .
bin/runwsgi -v etc/zope.ini
```
And get a paste#http based server with repoze.tm2 set up. I tried using waitress instead, but it immediately complains about WSGI requests not supporting hop-by-hop headers. I'm guessing that's related to the "Connection" header we emit, but didn't dig in further.

I tried adding repoze.retry, but doing so results in ``AssertionError: app must call start_response before returning``.

Currently any exceptions, for example NotFound are also not rendered as HTML back to the client, but only show up on the console. I tried WebError and paste:httpexceptions without luck.

Help or advice welcome.

**Comment by hannosch** [comment]
repoze.tm2 2.0b1 and later have a problem and don't work for us. They fail with the `app must call start_response before returning` assertion error. This is likely related to the changes from expecting a list to a generator (repoze/repoze.tm2#1 and repoze/repoze.tm2#3). Sticking to repoze.tm2 1.0 works for now.

Otherwise I managed to use waitress instead of the paste#http server. According to PEP 333, a WSGI app must not emit hop-by-hop headers like connection or transfer-encoding. I removed code to do so from the WSGIPublisher.

Finally I added basic exception handling / rendering support with a new Zope2#httpexceptions middleware mirroring what paste#httpexceptions did, but catching `zExceptions.HTTPException` and rendering it appropriately. I also extended that middleware to catch any other exception and wrap it in the standard HTML error boilerplate. This middleware isn't configurable, but serves as a default example. IIRC there are about five different ways to influence exception rendering in non-WSGI Zope and we decided not to support those at all for WSGI, as exception handling now happens outside of a local ZCA and transaction context. So no persistent standard_error_message template and no Zope Toolkit exception views.

**Comment by goschtl** [comment]
He Hanno,

do you had a look to infrae.wsgi. IIRC it works without major problems in some old projects?

Christian

**Comment by hannosch** [comment]
@goschtl thx for the reminder. I didn't remember infrae.wsgi anymore. It looks like that project is no longer maintained though.

repoze.retry and tm2 have seen recent activity and maintenance and the WSGIPublisher code in Zope2 required those. So I was hoping these were good enough and still worked today.

I've now gone ahead and at least made repoze.tm2 optional, by integrating the transaction begin/abort/commit calls back into the WSGI publisher, made conditional on the presence of repoze.tm2 in the WSGI pipeline.

I think the lesson from pyramid and pyramid_tm was that WSGI middleware's aren't actually a good idea, as you lack the context of and access to any application state. So infrae.wsgi's approach of keeping everything in one monolithic WSGI app might be better.

I'll have a bit more of a look to see if we can move transaction retry and error view functionality back into the publisher as well.

**Comment by leorochael** [comment]
@hannosch, From my work on [LongRequestLogger](https://github.com/zopefoundation/Products.LongRequestLogger) and [ZServerViews](https://pypi.python.org/pypi/Products.ZServerViews), two things became clear:

 - 1. As you realized, the previous work to WSGIfy Zope was enamoured with the ideas of middleware and tried to split parts of the request handling of Zope2 into their respective middlewares.

The result of that is that they sliced off Zope2 at the wrong spot to try to cut out a WSGI App. Instead of cutting inside ZPublisher, they should have cut inside ZServer.

 - 2. The implementation was botched and turned the ZPublisher from a generic module publisher into a publisher that can only publish the module `Zope2`. (I added a monkey patch for unbreaking that on the `Products.ZServerViews.tests.common` in [ZServerViews](https://pypi.python.org/pypi/Products.ZServerViews)).

The place to cut inside ZServer is actually quite simple, and ZServer itself is almost a WSGI server, except for two tiny bits in  the `zhttp_handler` class:

 - The `module` parameter, which instead should be a reference to the WSGI app or middleware to publish
 - The part in the `continue_request()` method where it instantiates a `ZPublisher.HTTPRequest.HTTPRequest` and calls `make_response` before adding them to a worker queue.

In the latter case, it should instead add to the queue just the `env` argument it already created (with the `sin` moved into `wsgi.input` key) along with an appropriate `start_response` the and the WSGI app that was passed in the constructor.

Then, in `ZPublisher`, you create a WSGI callable that itself creates an `HTTPRequest` with the stdin and environment, and an HTTPResponse with the `start_response` object that was passed in, and presto! You have a fully functional Zope2 WSGI server with all bells and whistles (retry, error rendering, persistent error log, etc..).

Anything else inside ZServer that depends heavily on anything inside ZPublisher, should be pushed inside `ZPublisher` itself (e.g. the whole `ZServer.HTTPResponse.ZServerHTTPResponse` class).

Bonus: by turning ZServer into a pure WSGI server, you'll have created an FTP WSGI server that converts FTP commands into WebDAV requests, thereby turning any WSGI app that expects WebDAV commands into an FTP server!

**Comment by icemac** [comment]
I gave a workshop back in 2011 describing how to run Zope using WSGI: https://icemac15.files.wordpress.com/2011/10/zope_2_as_wsgi_application.pdf
That's (mostly (?)) they way we run union.cms nowadays.

**Comment by hannosch** [comment]
I have made a good bunch of progress on this, and we now have a wsgi publisher in Zope 4, which has transaction and retry logic baked in again. It also supports exception views and the full range of pubevents. It does not support exception handling based on persistent objects like error_log or standard_error_message.

This currently replaces the WSGIPublisher we had in Zope 2.13 so support for a repoze (tm/retry) based publisher is gone. I think this is the right thing for the majority of projects, but it assumes that almost nobody used the middleware-driven approach. I think overall for the Python community that's true, and Pyramid moving to tweens instead of middlewares is a strong signal, but it might not be quite as true for Zope based projects.

I also moved ZServer, ZPublisher.Publish and all startup and configuration logic into a new project, and made all of it optional. This should allow us to port Zope to Python 3 without having to port ZServer and all its webdav/ftp/xmlrpc support code at the same time. If there is enough interest in porting it as well, it can be done, but it is no longer a blocker. With waitress we have now use a default web server, which is basically ZServer twice cleaned up, via the intermediate zope.server rewrite.

I've also updated the install and configuration docs and documented major changes in the what's new document, all found at http://zope.readthedocs.io/en/latest/index.html.
