### ISSUE TITLE
cannot add PythonScript from ZMI

### ISSUE THREAD

**Issue by ghiodor** [zopefoundation/Zope#669]
When I add a PythonScript and fill in the form with:

```
id = 'script'
title = ''
file = <ZPublisher.HTTPRequest.FileUpload object at 0x7f76a438d4f0>
'Add and Edit'
```
Note: I did not actually added a file, I would say file should be None.

I then get the following error:
```
Traceback (innermost last):

    Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
    Module ZPublisher.WSGIPublisher, line 337, in publish_module
    Module ZPublisher.WSGIPublisher, line 247, in publish
    Module ZPublisher.mapply, line 85, in mapply
    Module ZPublisher.WSGIPublisher, line 61, in call_object
    Module Products.PythonScripts.PythonScript, line 81, in manage_addPythonScript
    Module Products.PythonScripts.PythonScript, line 128, in __init__
    Module Products.PythonScripts.PythonScript, line 279, in _makeFunction
    Module Products.PythonScripts.PythonScript, line 250, in _compile
    Module Products.PythonScripts.PythonScript, line 273, in _newfun

IndexError: list index out of range

```
The offending line is the second (so safe_locals is empty): 

```
six.exec_(code, safe_globals, safe_locals)
func = list(safe_locals.values())[0]

```

**Comment by d-maurer** [comment]
The error actually comes from an incompatibility of `RestrictedPython` and `Products.PythonScripts`:
`RestrictedPython.compile_restricted_function` produces the following byte code:
```
              0 LOAD_CONST               0 (<code object script at 0xb5f32910, file "Script (Python)", line 1>)
              2 LOAD_CONST               1 ('script')
              4 MAKE_FUNCTION            0
              6 STORE_GLOBAL             0 (script)
              8 LOAD_CONST               2 (None)
             10 RETURN_VALUE
```
When this code is `exec`ed, the function ("script") is stored in the "globals dicts" while `Products.PythonScripts` expects it in the "locals dict".

The error is not restricted to the ZMI (or any input values). The easiest way to reproduce it is:
```
from Products.PythonScripts.PythonScript import PythonScript
s = PythonScript("script")
```

**Comment by d-maurer** [comment]
The `STORE_GLOBAL` at code position `6` should likely be a `STORE_NAME`.

The error is associated with the id "script": Python scripts (like e.g. PageTemplates) support the concept "bound name", names that are defined automatically and get values from the environment. For "Script Python" the bound names are 'context', 'container', 'script', 'traverse_subpath'. For `RestrictedPython` those bound names are "global"s. As a consequence, if your script uses as id any of those names, you will get the error you have observed (because the function arrives in the "globals dict" and not in the "locals dict").

Thus, avoid those ids and you should be fine.

If you have the strong feeling that `Products.PythonScripts` should provide a better error message for those cases, please file a corresponding bug report there.

**Comment by ghiodor** [comment]
Dieter, could you post the steps you took to arrive at the byte code? are the docs for zope 2.12 still helpful for debugging? https://zope.readthedocs.io/en/latest/zdgbook/TestingAndDebugging.html

**Comment by d-maurer** [comment]
ghiodor wrote at 2019-7-5 12:43 -0700:
>Dieter, could you post the steps you took to arrive at the byte code? are the docs for zope 2.12 still helpful for debugging? https://zope.readthedocs.io/en/latest/zdgbook/TestingAndDebugging.html

I stepped through the code (using the debugger).
I used `dis.dis` (`dis` is a module in Python's runtime library)
to get a readable representation of the byte code.
I did not look at documentation.
