### ISSUE TITLE
How to deactivate Chameleon and activate "standard template engine" again

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#728]
When I install a vanilla Zope via 
- git clone ...
- create venv
- $ bin/buildout -c zope-ecosystem.cfg
- $ bin/mkwsgiinstance -d .
...

What steps do I have to do to deactivate Chameleon and activate the "standard/old template engine" again?

If there is a zcml file involved, please be specific how to name it and where to put it with what kind of content, as I am not very familiar with those files.

Thank you!

P.S.: I saw the discussion in #717 but did not want to hijack that topic.
P.P.S.: I need this on a vanilla Zope with no own product installed as I try to reproduce a bug in https://github.com/zopefoundation/Products.ZCatalog/issues/84

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2019-11-7 14:14 -0800:
>When I install a vanilla Zope via
>- git clone ...
>- create venv
>- $ bin/buildout -c zope-ecosystem.cfg
>- $ bin/mkwsgiinstance -d .
>...
>
>What steps do I have to do to deactivate Chameleon and activate the "standard/old template engine" again?

One way would be to use `z3c.unconfigure` and
unconfigure the registration `<utility component=".engine.Program" />`
from `Products.PageTemplates:configure.zcml`.

If you need this only temporarily, you could comment the registration
directly in its zcml file.

**Comment by jugmac00** [comment]
Hi @d-maurer 
once again, thank you very much for your help.

Afaik there is no documentation about this and fiddling around with "engine.Program" with no mention of "Chameleon" seems very unapparent to me.

I'd like to keep this issue open until there is some documentation about how to configure the template engine for Zope.

A good place could be
https://zope.readthedocs.io/en/latest/zopebook/ZPT.html

**Comment by dataflake** [comment]
I don't understand the use case of wanting to switch to the old engine. As far as I know you can consider it dead. No one will do development on it.

Even if there were another _supported_ engine, switching would still be such a super rare case that is not done by "normal" users.

**Comment by jugmac00** [comment]
On the "What’s new in Zope 4" page it reads like this...
"...the Chameleon based engine is now the default..."
https://zope.readthedocs.io/en/latest/zope4/news.html#page-templates-now-rendered-by-chameleon

There is no mention of deprecating or even dropping support for the old template engine.

If there are plans, please do announce them and also issue deprecation warnings when using the old template engine.

As I only know one Zope application, I have no insight how many projects out there are not yet using Chameleon - maybe @icemac can give some input here.

My very subjective use case of switching back is simple - my application uses the old engine. Migrating my app to Zope 4 was and still is already massive work as there were tons of breaking changes.

Porting these 500+ templates will be an inevitable step, but I am not keen to perform it right now.

**Comment by dataflake** [comment]
I think you're misunderstanding the significance of the current hidden ability to switch template engines, why we switched and Chameleon's history.

First of all, switching the template engine isn't documented because there is no other supported template engine around. It was just put in as a contingency in case there are other implementations.

Chameleon is not something entirely different, the code base came from the built-in page template code. As far as I know Malthe separated it into its own project so TAL/TALES can be used easier outside of Zope. He also added fixes and features over time. For Zope it was a good thing. Zope developers can now rely on the Chameleon community for fixes and improvements. 

As you found out,  there's no easy way to switch engines, so it is safe to say that nearly EVERYONE who used page templates in Zope and who switched to Zope 4 is now using Chameleon.

I have gone through a large-scale migration and yes, the parser is much stricter in many places. This is clearly spelt out with examples in our own documentation at https://zope.readthedocs.io/en/latest/zope4/migration/content.html#page-template-parsing-issues. For my migration it was just a matter of scripting a large-scale search and replace of ZODB template content. Filesystem content is much easier, of course.

Trying to avoid the one-time migration by forcing the old engine seems a bad upgrade strategy to me. At best, you're just pushing that work out into the future. And you'd be running on an unsupported page template engine that is slated to be removed.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2019-11-8 04:05 -0800:
>I don't understand the use case of wanting to switch to the old engine. As far as I know you can consider it dead. No one will do development on it.

At the moment, there are two use cases:

 1. Users of `Products.TrustedExecutables` must use the old templating engine as it is not yet compatible with `chameleon`.

 2. Applications which need additional TALES expression types or specialized implementations of TALES expression types (e.g. for `Products.TrustedExecutables`) must use the old templating engine -- due to #717.

From my point of view, the `chameleon` integration is not yet well done (see #717) and apparently immature.
In addition, I had to spend several hours to analyse a syntax error very badly handled by `chameleon`.
These can be further reasons not yet to switch to `chameleon`.

**Comment by dataflake** [comment]
I'm afraid I have never even heard of `Products.TrustedExecutables`. I still maintain that wanting to switch the page template engine to the unmaintained old implementation is a niche usecase and not future-proof in any way. Of course Chameleon is not perfect, nothing is. But it's there and the integration works sufficiently well.

**Comment by dataflake** [comment]
And by the way, sure, if you guys actually find people who are willing to maintain the old engine then making it easier to switch back to it has value. But only then. Otherwise you're betting on an uncertain future.

**Comment by jugmac00** [comment]
Looks like this is a "hidden" feature on one's own risk, so I do not think it is a good idea to put it in the official documentation.

I close this issue.

Thank you for you help!
