### ISSUE TITLE
Future of ZServer

### ISSUE THREAD

**Issue by mtoepfl** [zopefoundation/Zope#742]
First of all, thank you for all the work you all did porting Zope to Python 3!

I red about the effort ripping out ZServer completely from Zope 5 #696 

Isn't that to early looking at the promising work @datakurre did in porting ZServer from Medusa to Twisted on Python 3.

We are porting our existing Zope applications over to ReactJS and Zope does a very good job in serving data over a GraphQL API implemented with python-graphene. With its object database and its event system it is possible to implement feature which are offered by "modern" application severs like https://hasura.io/ very easily. Also performance is really good!

The only thing we miss is the async stuff. We need a way to notify the client about changes on the server over websockets.

I visited the following talk @datakurre gave at Plone Conf 2019:
https://datakurre.github.io/ploneconf2019/zserver-reloaded-with-http2-and-websocket-support.pdf

I tried out the PubSub-socket over ZServer and it works like a charm in Twisted and Python 3.

My question is, which is the recommended way to go? Zope over wsgi? Will there be asgi support in near future? Is there a chance to keep async ZServer in Twisted in mainstream? Which way Plone people will go for async challenges?

I'm not sure if I remember right, but I think @datakurre mentioned it's not as easy to implement with asgi as with Twisted because of the different threading models. But I'm not very experienced in this area.

**Comment by dataflake** [comment]
The decision to go with WSGI has been made a long time ago. It's not up for disposition. Please also remember that the support code inside Zope itself has a cost. It must be maintained and tested. I haven't seen anyone step up.

**Comment by mtoepfl** [comment]
Thank you @dataflake for your fast answer and the new release you did. I'm sorry, I posted my issue inadvertently during writing it. I gave more information and added my concrete question by editing the issue.

**Comment by dataflake** [comment]
I don't really know much about websockets so I can't help you on that.

**Comment by datakurre** [comment]
@mtoepfl FWIW, while I haven't been able to try Zope 5, I assume that "my ZServer" is not too far from working on it, because the code already uses the WSGI ZPublisher maintained in Zope 5.

But WebDAV support is really gone in Zope 5 with dropped ZServer support. I've understood that it could be restored in Zope (without depending on ZServer) if someone would champion it, as discussed in https://github.com/zopefoundation/Zope/issues/649

I really don't know much about ASGI yet. About WSGI and WebSockets in general I had the understanding that any solution would be more or less tied to some specific WSGI server, so I could as well implement it into ZServer, which I understand better than the other servers.

**Comment by dataflake** [comment]
@datakurre Asking with a complete lack of knowledge about your ZServer work, just out of curiosity: Can is be made WSGI compatible so it can be plugged in like any other WSGI server?

**Comment by datakurre** [comment]
@dataflake My ZServer works like the old ZServer. I don’t understand how WSGI support would make sense there, because it is already here (in Zope). To make ZServer work with Python 3, I ”simply” replaced Medusa based servers with servers from Twisted (like Zope did optionally for some time years ago). I also did not port the old publish-method to Python 3, but used the one already ported in Zope for WSGI (so I do wrap requests into WSGI request before passing them to ZPublisher).

**Comment by dataflake** [comment]
I was just wondering in terms of how the "new" ZServer communicates with Zope itself. Since Zope acts as a WSGI application i sounded like a logical "plug-in" point.

**Comment by datakurre** [comment]
@dataflake Oh, sorry. I only now understood your original question. I believe it is not that far from doing that already by using ZPublisher.WSGIPublisher.publish_module.

**Comment by dataflake** [comment]
I would summarize like this:

- Zope is now a WSGI application and does not have its own webserver, so questions regarding web sockets or PubSub or asynchronous service etc no longer apply to Zope itself. These questions are for the different web servers that you can hook up to Zope, be it WSGI servers or the "new" ZServer
- the previous ZServer integration bits have been removed, this is true. But from @datakurre I get the impression that they are not needed for his implementation, anyway. So any claim that (the new) ZServer is not supported appear to be wrong.

@datakurre Have you tested with Zope `master` (Zope 5)? If there's anything we can reasonably do to make it work that doesn't involve large customizations I am sure we can get it done.

**Comment by dataflake** [comment]
I suggest questions about network protocol support be moved to either WSGI server support pages or the new ZServer project.

I have opened a separate issue to re-integrate the WeDAV support code.

For any compatibility issues @datakurre has integrating ZServer in Zope 5 he can file separate tasks here.

If there are no objections I would like to close this particular issue.

**Comment by datakurre** [comment]
@dataflake I agree with your reasoning. Thank you. I have not had time to test against the master yet, but changes looked to be mostly about removed deprecated imports and WebDAV.

I am sure that my branch won’t work OOTB, because it imports WebDAV classes from Zope. I’d expect that removing WebDAV support from ZServer and fixing imports would make it work.

I don’t need Zope 5 yet, so I might wait for some time to see the conclusion of WebDAV future in Zope (and Plone), before I look into this in more detail.

**Comment by datakurre** [comment]
@mtoepfl If you come to conclusion that my ZServer would be good option for you, then you could open possible issues there. My own schedules for getting it into production have not realised yet...

That said, I’d expect it to be solid already because of Twisted and other well tried libraries, but I’d welcome testing for things like error views and logging.

Sure there are a l out of chores on removing all old Medusa code, updating tests and docs. Also I should get my CLA paperwork done to make the licensing Zope compatible.

**Comment by dataflake** [comment]
@datakurre the conclusion for WebDAV's future in Zope itself is quite clear - I will add the support code back in before Zope 5 lands (see #744 )

**Comment by dataflake** [comment]
FYI, the re-integration has landed on `master` and #779 for the `4.x` branch is open for review. It will go into the next Zope 4 release (4.2).

**Comment by dataflake** [comment]
FYI, Zope 4.2 is now released and it contains the WebDAV support code. So will all Zope 5 releases once we start making them.

As I understand this is (for now) all Zope itself can do to help the standalone ZServer project on their way to new releases. I will close this issue here but want to encourage everyone to open new issues if there is any additional support Zope itself can provide.

Any general discussion regarding ZServer and its future should continue on the ZServer issue tracker at https://github.com/zopefoundation/ZServer/issues.
