### ISSUE TITLE
zope3 compatibility

### ISSUE THREAD

**Issue by AngelPujaa** [zopefoundation/Zope#780]
can we use zope3 with Python3 or not?

**Comment by jugmac00** [comment]
Zope's naming history is quite evolved.

There is **Zope 2** (newest version 2.13, but Py 27 only), which got updated to **Zope 4**, which works both with Python 2 and Python 3. The current development version is **Zope 5**.

This repository is about Zope 2/4/5.

When you speak of **Zope 3**, this was the (partly) incompatible successor of **Zope 2**. In order to reduce the naming confusion, it was renamed to **BlueBream**. Zope 3/BlueBream was not easy to configure, so an fork with the name **Grok** was created, which was easier to configure.

I do not know anything about the latter two, but I suspect there are no working Python 3 versions.

**Comment by goschtl** [comment]
Hey,

i am pretty sure that Zope3 is running on Python3 and Grok too.

Christian

Am Fr., 7. Feb. 2020 um 08:57 Uhr schrieb Jürgen Gmach <
notifications@github.com>:

**Comment by jugmac00** [comment]
@goschtl This would be great news!

It is not that easy to get information about the current state.

For Grok I looked here:
https://github.com/zopefoundation/grok/issues/3

And for BlueBream I looked here:
https://launchpad.net/bluebream

And that looked not that good.

But when you look at Grok's setup.py... it should actually work:
https://github.com/zopefoundation/grok/blob/990a8437891cfc8694c789070a52521c480cca73/setup.py#L45-L51

I leave this to the one's who are acutally involved in these projects.

**Comment by AngelPujaa** [comment]
can anyone provide the link for building web application using Zope4 because the documentation is not very clear about it?So,i need a help that anyone provide the link for building application in zope4 stepwise.

**Comment by AngelPujaa** [comment]
is bluebream and zope3 are same?

**Comment by d-maurer** [comment]
AngelPujaa wrote at 2020-2-7 01:21 -0800:
>can anyone provide the link for building web application using Zope4 because the documentation is not very clear about it?So,i need a help that anyone provide the link for building application in zope4 stepwise.

"Zope 4" is the successor of "Zope 2". Thus, most of the Zope 2
documentation is still valid. Start at "https://www.zope.org/".
For "Zope 4" specifics, look at "https://zope.readthedocs.io/en/latest/".

**Comment by AngelPujaa** [comment]
bluebream and zope3 are same ?

**Comment by jugmac00** [comment]
The English Wikipedia article says so...

https://en.m.wikipedia.org/wiki/Zope

**Comment by AngelPujaa** [comment]
I am migrating from zope3 to zope4. So, i have one application in zope3 so i want to upgrade it zope4. How can i update the code of zope3 in zope4?

**Comment by dataflake** [comment]
There is no direct upgrade path, sorry. Zope 3 is based on a different technology stack and has very little to do with Zope 4 (and its predecessor, Zope 2).

**Comment by AngelPujaa** [comment]
I don't want to code for any file in zope4 ZMI. In zope3, i created the lib and python folder and inside it i buid the application so the same thing i want to do in  zope4. How can i do this?

**Comment by AngelPujaa** [comment]
In documentation of zope4, everthing is done in ZMI. But i don't want to do anything directly in ZMI. I want to build files and folder as we did in zope3 ,then the effect is visible to Zope4 ZMI. How can i do this?Please guide me.

**Comment by dataflake** [comment]
This is an issue tracker for bugs and feature requests fo Zope2, 4 and 5. This is not the place to get basic programming information, and this is not a Zope 3 foum. I repeat: There is no direct upgrade path.

**Comment by AngelPujaa** [comment]
Is this possible to upgrade my zope3 application using python3 version?

**Comment by dataflake** [comment]
I am sorry, I will need to close this. Please understand, we cannot help you here. This is the wrong place.

**Comment by jugmac00** [comment]
@AngelPujaa You could try to post at the Plone community forum in the Zope section
https://community.plone.org/

Also, they have a job section. If you want commercial support, this is the place to go.

**Comment by d-maurer** [comment]
AngelPujaa wrote at 2020-2-7 05:35 -0800:
>Is this possible to upgrade my zope3 application using python3 version?

"Zope3" (like Zope2 and Zope 4) consists of a large number
of individual packages, many of those used by all Zope variants.
In order to use your application with Python 3, all the
packages it is using will need to be Python 3 compatible.
For those packages used by both "Zope 3" and "Zope",
Python 3 compatible packages exist --  your application needs only
to include new versions of them; for other packages, you
must find out whether there exist and/or how to obtain Python 3
compatible versions. Often, it is not difficult to make
a package Python 3 compatible.

As Jens (and others) wrote: "Zope3" is not "Zope" (despite its name)
(however many packages are shared). We cannot help you here
with a "Zope3" upgrade path.

**Comment by icemac** [comment]
@AngelPujaa 
Yes, Zope 3 (aka Bluebream) runs on Python 3. I do not see the need for a Zope 3 application to be ported to Zope 4. Keep it on Zope 3 but upgrade it to run on Python 3. If there are any problems use the issue tracker of the package where the problem arises.
