### ISSUE TITLE
Zope 4 ZMI: some links do not work when Zope is deployed under a prefix (e.g. "/api")

### ISSUE THREAD

**Issue by tisto** [zopefoundation/Zope#788]
Deploying the Plone REST API under "/api" (via Apache or Nginx) is considered best practice in the Plone community for a variety of reasons (CORS not working well in production, classic Plone needs to stay available).

When doing so, some essential links in the ZMI are not working:

![ZMI](https://user-images.githubusercontent.com/632105/74779544-01feaf00-529e-11ea-9a02-401d55a01936.png)

Examples: 

- Control Panel
- ZODB Main
- ZODB Temporary
- Undo

The reason those links are not working is that they are missing the "/api" prefix. E.g. for "Undo":

```
https://mydomain.com/Control_Panel/Database/main/manage_UndoForm
```

It should be:

```
https://mydomain.com/api/Control_Panel/Database/main/manage_UndoForm
```

Python Version: 3.7
Plone Version: 5.2.1
Zope Version: 4.1.3

cc @pbauer @jensens issue filed as promised :)

**Comment by dataflake** [comment]
Can you provide Apache RewriteRule examples that you use so I can set up a test sandbox?

**Comment by tisto** [comment]
@dataflake sure! Thanks for the swift response! :)

**Comment by tisto** [comment]
@dataflake here is an example copied from one of our live servers. It is the full Apache config for the Plone backend and the Volto/React frontend. It also uses Apache load balancing. I am not fluent with Apache so I just paste the full config here. 

I think the "RewriteRule     ^/api($|/.*)" line is the only important one here.

```
<Proxy balancer://backend>

  ProxySet lbmethod=bybusyness
  BalancerMember http://127.0.0.1:8001

</Proxy>

<Proxy balancer://frontend>

  ProxySet lbmethod=bybusyness
  BalancerMember http://127.0.0.1:8010

</Proxy>

RewriteEngine On
ProxyPreserveHost On

RewriteCond     %{ENV:HTTP_VHOST}       example\.com$  [NC,OR]
RewriteCond     %{ENV:HTTP_VHOST}       ^example\.com$  [NC]
RewriteRule     (.*)                    https://www.example.com$1  [R,L]

RewriteCond     %{ENV:HTTP_VHOST}       ^www\.example\.com$  [NC]
RewriteRule     ^/api($|/.*)            balancer://backend/VirtualHostBase/https/www.example.com:443/Plone/VirtualHostRoot/_vh_api$1  [P,L]

RewriteCond     %{ENV:HTTP_VHOST}       ^www\.example\.com$  [NC]
RewriteRule     ^(.*)                   balancer://frontend$1        [P,L]

ProxyPassReverse        /               balancer://frontend/
```

I can also provide our Nginx config, if that helps or ask one of my collegues who is more into the ops stuff for a simpler config if necessary. cc @sneridagh

**Comment by dataflake** [comment]
This is fine and yes, the one RewriteRule you pointed out is the important one. I just want to make sure I am testing as closely as possible to that real-world scenario.

**Comment by dataflake** [comment]
Try the head of the `4.x` branch or `master`, there's fixes on both. There's probably a lot more places where this kind of stuff happens, the new ZMI has way too many hardcoded URLs in it.

**Comment by tisto** [comment]
@dataflake awesome! Thank you for the quick response and for fixing this right away! I will give it a shot and report back.

**Comment by jugmac00** [comment]
Glad to see this fixed! Thank you!

FWIW, this issue is a duplicate of #765 which was closed as invalid three weeks ago.

It would be great to have it documented somewhere that Zope does support non root deployments, so that e.g. Zope product developers know this, and should test their products to support this mode.

I am not sure where the best place would be... 

We have this up-to-date documentation about ZMI, but this is more related to bootstrap.
https://zope.readthedocs.io/en/latest/migrations/zope4/code.html#migrating-to-the-new-bootstrap-based-zmi

We have a chapter about ZMI in the Zope book, but it is only about using it.

And there is nothing in the Zope developer book.

P.S.: @tisto 
I experienced the same problem and I'd like to test it, also.

I am not very familiar with Mr. Developer and co.

Could you please post the relevant sections of your buildout.cfg which allows you to test Zope from GitHub instead of from PyPi?

Thank you very much.

**Comment by dataflake** [comment]
#765 appeared to have a much larger scope and that's why I closed it. This one was for a few specific links that were easy to tackle. As I mentioned here, I am sure there are lots more, so I stand by what I said in #765: Non-root deployments are not officially supported. Not just because no one has found the time to dig through every line of ZMI code and root out those broken absolute links that can be found all over it, but also because no one here can say if the countless Zope add-ons that offer ZMI screens work in a non-rot deployment.

**Comment by tisto** [comment]
@dataflake I can confirm that the broken links that I reported are fixed with Zope4.2.2.dev0, python 3.7.5. Thank you for the fix and the swift reply!

Just a note: the non-root use case is quite important for the Plone community since Plone ships with plone.restapi since 5.2 and the new Volto frontend that will ship with Plone 6 requires a non-root deployment of the Plone backend under /api. There is no other way to make Plone work with a modern JS frontend that I would know about that works reliably. 

I am not saying that everything in the ZMI needs to work or that we expect the Zope community to do all the work. I just want to stress the fact that if Zope stops working under a non-root deployment altogether, we (the Plone community) would be screwed.

**Comment by dataflake** [comment]
There are no plans to make it "not work". The problem here is the new ZMI. There are many places where it just makes the assumption that the ZMI is anchored at `/`. Finding all those requires a code audit for all ZMI view code, Javascript and in some places even styles.

**Comment by tisto** [comment]
@jugmac00 here you go:

`````
[buildout]
...
extensions = mr.developer
auto-checkout = *

...

[sources]
Zope = git https://github.com/zopefoundation/Zope.git pushurl=git@github.com:zopefoundation/Zope.git branch=4.x
...
`````
