### ISSUE TITLE
Zope4 and python application development

### ISSUE THREAD

**Issue by hekl** [zopefoundation/Zope#815]
Zope 2 was originally followed by zope 3, which had a completely new way of using python in zope applications. I never used it. Does zope 4 still support this zope 3 development? And if so, why is there no hint of it in the zope 4 documentation? Am I missing something?

**Comment by d-maurer** [comment]
Henk Laloli wrote at 2020-4-12 14:35 -0700:
>Zope 2 was originally followed by zope 3, which had a completely new way of using python in zope applications. I never used it. Does zope 4 still support this zope 3 development? And if so, why is there no hint of it in the zope 4 documentation? Am I missing something?

Zope 3 has two constituents: a large number of widely usable packages,
collectively called the "Zope toolkit" and used to implement the
so called "Zope component architecture", and an application server
(build on top of those).

Zope 2 (modern versions thereof) and Zope 4 use a significant part
of the "Zope toolkit" and you can use (most of) the
"component architecture" (i.e. views, utilities, adapters, subscribers,
events, ...) in your application. However, they have their own
application server (and security concept).

I have seen (somewhere in the documentation) the hint that
Zope 4 is **NOT** a successor of Zope 3, but of Zope 2:
Applications built on the basis of Zope 3 will require significant
changes to be made compatible with Zope 4.
I have learned in a similar discussion (either here of
in the "Zope" category of "https://community.plone.org")
that the Zope 3 application server was factored into its own
package. Likely, it is a better approach for Zope 3 application
to use this package (rather than Zope 4).

**Comment by dataflake** [comment]
Zope 2 was never "followed" by Zope 3. It was its own thing that never managed to replaced Zope 2. Zope 3 as a standalone application server is dead and has been for many years.

Zope 4 is the successor of Zope 2.  Apart from shared use of some packages there was never any overlap with Zope 3 in how you develop for them. That's why Zope 3 was never mentioned in the Zope 2/4 documentation, and the Zope 3 documentation never mentioned Zope 2.

**Comment by hekl** [comment]
Maybe I should rephrase the question. What is the way of developing zope4 applications with python? Is there documentation on this?

**Comment by dataflake** [comment]
The official documentation for Zope 4 is at https://zope.readthedocs.io/en/4.x/  and some older resources are at https://www.zope.org/documentation/index.html
