### ISSUE TITLE
Updating dependecy versions?

### ISSUE THREAD

**Issue by jensens** [zopefoundation/Zope#817]
While I updated Plones ``versions.cfg`` to for with use the current master, I found there are some outdated version in Zopes ``version.cfg``.

What is the process of updating those here? PR or is this a Release Manager job?

I found we have ``requirements-*.txt`` and ``version-*.cfg``. Is there a script to keep those in sync?

**Comment by dataflake** [comment]
Normally this is a release manager job and dependency versions are only updated right after a release has been made so that there is as much time for interoperability testing as possible.

If a newer dependency is required to fix specific issues it can be updated at any time. Updating the version in `versions-prod.cfg` or `versions.cfg` and then running `bin/buildout` will update the `.txt` files.
