### ISSUE TITLE
The method  bobobase_modification_time()  is not supported with Zope 4

### ISSUE THREAD

**Issue by raeuz** [zopefoundation/Zope#851]
I tried the example given from:https://github.com/zopefoundation/Zope/blob/master/docs/zopebook/SimpleExamples.rst#step-14-adding-index_html-script-and-template

This example raises exception as the bobobase_modification_time() does not exist with Zope 4.

**Comment by dataflake** [comment]
The Zope Book has been written for Zope 2 and there have been many changes on the way to Zope 4. That's why that page was marked at the top as written for Zope 2.

I have made some minor changes to that page, so if you reload https://zope.readthedocs.io/en/4.x/zopebook/SimpleExamples.html you should be able to follow that tutorial all the way.
