### ISSUE TITLE
Products.Pagetemplates: switch/case does not work anymore for Zope > 4.3

### ISSUE THREAD

**Issue by ale-rt** [zopefoundation/Zope#862]
Tested in Plone buildout.coredev.

This snippet:
```
        <div tal:define="key string:foo"
             tal:switch="key"
        >
          <tal:bar case="string:bar">bar</tal:bar>
          <tal:default case="default">baz</tal:default>
        </div>
```
Used to render:
```
<div>baz</div>
```
Now it does not render anything because `default` is not set to the value of key.

Note if I keep chameleon 3.8 and switch back to Zope 4.3 the behavior is the expected one

**Comment by ale-rt** [comment]
As a workaround I can change the default with `<tal:default case="key">baz</tal:default>`

**Comment by d-maurer** [comment]
Alessandro Pisa wrote at 2020-7-3 03:58 -0700:
>Tested in Plone buildout.coredev.
>
>This snippet:
>```
>        <div tal:define="key string:foo"
>             tal:switch="key"
>        >
>          <tal:bar case="string:bar">bar</tal:bar>
>          <tal:default case="default">baz</tal:default>
>        </div>
>```
>Used to render:
>```
><div>baz</div>
>```
>Now it does not render anything because `default` is not set to the value of key.

@malthe
I assume this is a `chameleon` issue:
recent `chameleon` versions have changed the `default` handling
from a local (ever changing) default marker towards a unique object.
Likely, this change was not applied to `tal:switch`.

**Comment by ale-rt** [comment]
Note: if I keep chameleon 3.8 and switch back to Zope 4.3 the behavior is the expected one. So I am suspect more a change in Zope pagetemplate handling.

**Comment by d-maurer** [comment]
Alessandro Pisa wrote at 2020-7-3 15:33 -0700:
>Note: if I keep chameleon 3.8 and switch back to Zope 4.3 the behavior is the expected one. So I am suspect more a change in Zope pagetemplate handling.

Yes and no:

The yes part:
`chameleon` used to work with local (ever changing) definitions
of the TALES `default` object. This means that with it, you did not have
a single `default` object but each template (and likely even each element
with a TAL/METAL attribute in a template) had its own representation
of `default`. This worked (in simple cases)
because the `chameleon.tales` TALES implementation has partial
access to the local variables of the calling rendering function --
among them the current `default` definition.
`zope.tales` is not designed to access local variables of the caller.
Therefore, it expects `default` to be a singleton, a unique global object
that can be used like any other value and does not need special treatment.
As a consequence, `default` no longer worked (for all `tal` attributes).

The no part:
@malthe has switched recently from local `default` definitions
to a global one. This fixed `default` handling for most
tal attributes. But, apparently `switch` still uses a local `default`
definition - and does therefore not work with `zope.tales`.


As a side note: the `attrs` problem has the same cause; this, too, is
one of the local variables of the rendering function which can directly be
accessed by `chameleon.tales` expressions - to make it available
with `zope.tales` the caller must help.

**Comment by d-maurer** [comment]
The problem has the following cause:
`chameleon` implements its `tal:case="default"` via a local redefinition of the "variable" `default` effective during the evaluation of the "case expression". The redefinition is not made via `econtext` (the usual place for variable bindings) but relies on the expression being able to access (some) local variables of the rendering function - among them the variable representing the current default value. Unlike a `chameleon.tales` expression, a `zope.tales` expression cannot access local variables of the rendering function (without special provisions in the integration).

@malthe I can work around this in the integration -- similar to how it now handles `attrs`. But, maybe, you are ready to avoid local redefitions of `default` in `chameleon`? Currently, `tal:case="expr"` is essentially implemented by:
```
default = cached_switch_expression
value = evaluate(expr) # this sees the local redefinition of `default`
if value == default:
  ... case taken ...
```
Without local `default` redefition this would look like:
```
value = evaluate(expr)
if value is default or value == cached_switch_expression:
  ... case taken ...
```
The difference regarding efficiency should be minimal. `value is default` is used elsewhere in `default` processing. Local redefinitions of a symbol with global semantics (like `default`) are conceptionally doubtful (I can construct examples giving wrong results - even though they are not of practical importance).

**Comment by malthe** [comment]
@d-maurer I have attempted to fix this in 287c99dea64529cae6673ce84c3025f3074c17d5.

As you mention, both switch/case and dynamic attributes were defining `default` in a non-symbolic way. And I think that in the name of staying true to the original language, `default` should be a symbolic value – not for example, a string that can be used in code.

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2020-7-5 07:31 -0700:
>@d-maurer I have attempted to fix this in 287c99dea64529cae6673ce84c3025f3074c17d5.


Thank you very much!

I will try this tomorrow.

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2020-7-5 07:31 -0700:
>@d-maurer I have attempted to fix this in 287c99dea64529cae6673ce84c3025f3074c17d5.

@malthe works - thank you again!

**Comment by d-maurer** [comment]
Thanks to @malthe this problem will be resolved by an upcoming `chameleon` version.

**Comment by ale-rt** [comment]
Thanks a lot @d-maurer and @malthe, I am really impressed for the quick reaction :bowing_man:

**Comment by dataflake** [comment]
Fixed by https://github.com/zopefoundation/Zope/commit/6bc4daed19134980a41b4185c7abdba5cd7ac1be on `4.x` and https://github.com/zopefoundation/Zope/commit/308b6fb991040ed0dc85994e69352862977bd9e9 on `master`
