### ISSUE TITLE
dtml-tree tag no longer shows expansion markers

### ISSUE THREAD

**Issue by mcgfeller** [zopefoundation/Zope#884]
Dear all

I'm not sure whether the [\<dtml-tree\> tag](https://zope.readthedocs.io/en/latest/zopebook/AppendixA.html#tree-inserts-a-tree-widget) is desupported, but on Zope 4.5.0 (Py3.8, on Win 10), it no longer shows the expansion marker. On Zope 2.13, it showed a + in a box to expand a subtree, and a - in a box to collapse a subtree. 

Or do I have to include something new to generate an expandable tree? 

Thank you! And great to have Zope on Py3.x!

Martin

**Comment by jugmac00** [comment]
Hi Martin,

for reasons unknown to me the icons were removed from Zope source while transitioning from Zope 2 to Zope 4.

I had the same problem when I migrated to Zope 4.

I checked out the 2.13 branch from Zope and copied / vendored the icons into my app.

**Comment by mcgfeller** [comment]
Danke, Jürgen!

This is unfortunately beyond my know-how of Zope, but it seems the code displaying the tree is in [DocumentTemplate.TreeDisplay.TreeTag](https://github.com/zopefoundation/DocumentTemplate/blob/master/src/TreeDisplay/TreeTag.py)

In Revision: 6af41a0957407a40e02210926c63810d7bbe53ff (07.03.2018) "No longer use icons which got deleted in Zope 4. (#16)", the icons were replaced by +/- strings. 

In Revision: 01b3da2378ecbcd7c77f8d7e23aa78f076aed14c (02.10.2018) the + / - was replaced by an "Icon", which seems to be invisible to me.  

If I undo the 2nd change, all is well. I have to figure out which the "Icon" is not displayed to me - seems to be a CSS issue. 

Thank you very much again for pointing me into the right direction.

**Comment by jugmac00** [comment]
When my former colleague introduced me to Zope 2007, he told me I could skip the DTML chapters of the Zope book, as DTML is obsolete - how wrong he was :-)

As I said, I have no experience with DTML, but I just had a look in my app's ZMI, and there the menu on the left uses dtml tree tag and it works.

The "icon" is no longer a real icon, nor it is a plain `+`  or `-` character - now it is an empty HTML tag. CSS inserts a special unicode character, which - with the help of a special font, gets rendered as an icon. At least that is how I understand this technique.

In order to track down the problem you encounter, you could try two things:
- go to your app's ZMI, and have a look at the menu at the left; this uses the dtml-tree-tag; make sure you have some nested structure; if not, please create a folder with some subfolders; does this work?
- in your browser, before visiting a view with a dtml-tree-tag, please open the "console", load a page with a dtml tree tag and have a look whether there is an error loading some assets, especially the fontawesome file

(open console: FireFox: ctrl+shift+k; Chrome: ctrl+shift+j)

**Comment by jugmac00** [comment]
Ok, I could reproduce some problems with rendering the icons

When I load `http://localhost:8080/level_a/manage_main` directly, I get a ton of warnings/errors:
![Screenshot from 2020-08-03 18-40-38](https://user-images.githubusercontent.com/9895620/89205967-dad03b80-d5b8-11ea-9377-efed128dcee7.png)

When I then show the menu via the show/hide tree menu button, the icons do not get shown!

![Screenshot from 2020-08-03 18-41-01](https://user-images.githubusercontent.com/9895620/89206095-09e6ad00-d5b9-11ea-9541-cdf025be3e03.png)

Also, a warning about "sameSite" attribute gets shown - which should be taken care of.

@mcgfeller Could you please confirm (via console) that you experience similar problems?

@drfho What is your take on this?

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2020-8-3 09:20 -0700:
> ...
>The "icon" is no longer a real icon, nor it is a plain `+`  or `-` character - now it is an empty HTML tag. CSS inserts a special unicode character, which - with the help of a special font, gets rendered as an icon. At least that is how I understand this technique.

From this description, I guess (!) that ZMI resources (the CSS magic)
may be necessary to get the icons displayed.

**Comment by mcgfeller** [comment]
Thank you @jugmac00 and @d-maurer a lot. It is exactly as you describe: CSS is used to display the icon with a special font. This requires the ZMI resources, which I didn't have. With this explanation, I can close it as _no bug_. As the change is old enough and DTML is really ancient, I think it is unlikely that somebody else will stumble upon it and hence it doesn't deserve a mention in the documentation. 

Nochmals vielen Dank an alle!
Martin
